# Generated by nix-android-repo

{ mkBuildTools
, mkCmdlineTools
, mkEmulator
, mkNdk
, mkNdkBundle
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSrcOnly
}: {
  add-ons-addon-google-gdk-google-19 = mkSrcOnly {
    id = "add-ons;addon-google_gdk-google-19";
    pname = "add-ons-addon-google-gdk-google-19";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/glass/google-gdk.zip";
        sha1 = "52cadbec4d42ce68a667e7e4ea461ef8b81924ef";
      };
    };
    displayName = "Glass Development Kit Preview";
    path = "add-ons/addon-google_gdk-google-19";
    license = {
      id = "google-gdk-license";
      hash = "33b6a2b64607f11b759f320ef9dff4ae5c47d97a";
    };
    xml = ./add-ons-addon-google-gdk-google-19.xml;
  };
  system-images-android-30-android-wear-cn-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;arm64-v8a";
    pname = "system-images-android-30-android-wear-cn-arm64-v8a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/arm64-v8a-30_r12.zip";
        sha1 = "ef7b5554a5f77fb33c7965604552411c155a38ac";
      };
    };
    displayName = "China version of Wear OS 3 ARM 64 v8a System Image";
    path = "system-images/android-30/android-wear-cn/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-arm64-v8a.xml;
  };
  system-images-android-30-android-wear-cn-x86 = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;x86";
    pname = "system-images-android-30-android-wear-cn-x86";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/x86-30_r12.zip";
        sha1 = "42548b2bd1696ad6bd2f01a1cf83ef7a10971932";
      };
    };
    displayName = "China version of Wear OS 3 Intel x86 Atom System Image";
    path = "system-images/android-30/android-wear-cn/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-x86.xml;
  };
  system-images-android-35-google-apis-playstore-tablet-arm64-v8a = mkSrcOnly {
    id = "system-images;android-35;google_apis_playstore_tablet;arm64-v8a";
    pname = "system-images-android-35-google-apis-playstore-tablet-arm64-v8a";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/arm64-v8a-35_r09.zip";
        sha1 = "6ce87d60c505338b8253f8f1de22547ac2a0bcb7";
      };
    };
    displayName = "Google Play Tablet ARM 64 v8a System Image";
    path = "system-images/android-35/google_apis_playstore_tablet/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-35-google-apis-playstore-tablet-arm64-v8a.xml;
  };
  system-images-android-35-google-apis-playstore-tablet-x86-64 = mkSrcOnly {
    id = "system-images;android-35;google_apis_playstore_tablet;x86_64";
    pname = "system-images-android-35-google-apis-playstore-tablet-x86-64";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/x86_64-35_r09.zip";
        sha1 = "a1254d64b76bfc001553e502eecdf66921393fbc";
      };
    };
    displayName = "Google Play Tablet Intel x86_64 Atom System Image";
    path = "system-images/android-35/google_apis_playstore_tablet/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-35-google-apis-playstore-tablet-x86-64.xml;
  };
  system-images-android-35-google-apis-tablet-arm64-v8a = mkSrcOnly {
    id = "system-images;android-35;google_apis_tablet;arm64-v8a";
    pname = "system-images-android-35-google-apis-tablet-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_apis_tablet/arm64-v8a-35_r02.zip";
        sha1 = "ee76689835d867058ecce51e6634635675c83482";
      };
    };
    displayName = "Google APIs Tablet ARM 64 v8a System Image";
    path = "system-images/android-35/google_apis_tablet/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-35-google-apis-tablet-arm64-v8a.xml;
  };
  system-images-android-35-google-apis-tablet-x86-64 = mkSrcOnly {
    id = "system-images;android-35;google_apis_tablet;x86_64";
    pname = "system-images-android-35-google-apis-tablet-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_apis_tablet/x86_64-35_r02.zip";
        sha1 = "4f497f7a4ed5965b162ab6a33b8f99e4d4163154";
      };
    };
    displayName = "Google APIs Tablet Intel x86_64 Atom System Image";
    path = "system-images/android-35/google_apis_tablet/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-35-google-apis-tablet-x86-64.xml;
  };
}