# Generated by nix-android-repo

{ mkGeneric
, mkBuildTools
, mkEmulator
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSystemImage
}:
{
  packages = {
    build-tools-17-0-0 = mkBuildTools {
      id = "build-tools;17.0.0";
      pname = "build-tools-17.0.0";
      version = "17";
      sources = {
        linux = {
          url = "build-tools_r17-linux.zip";
          sha1 = "2c2872bc3806aabf16a12e3959c2183ddc866e6d";
        };
        darwin = {
          url = "build-tools_r17-macosx.zip";
          sha1 = "602ee709be9dbb8f179b1e4075148a57f9419930";
        };
        windows = {
          url = "build-tools_r17-windows.zip";
          sha1 = "899897d327b0bad492d3a40d3db4d96119c15bc0";
        };
      };
      displayName = "Android SDK Build-Tools 17";
    };
    build-tools-18-0-1 = mkBuildTools {
      id = "build-tools;18.0.1";
      pname = "build-tools-18.0.1";
      version = "18.0.1";
      sources = {
        linux = {
          url = "build-tools_r18.0.1-linux.zip";
          sha1 = "f11618492b0d2270c332325d45d752d3656a9640";
        };
        darwin = {
          url = "build-tools_r18.0.1-macosx.zip";
          sha1 = "d84f5692fb44d60fc53e5b2507cebf9f24626902";
        };
        windows = {
          url = "build-tools_r18.0.1-windows.zip";
          sha1 = "a6c2afd0b6289d589351956d2f5212b37014ca7d";
        };
      };
      displayName = "Android SDK Build-Tools 18.0.1";
    };
    build-tools-18-1-0 = mkBuildTools {
      id = "build-tools;18.1.0";
      pname = "build-tools-18.1.0";
      version = "18.1";
      sources = {
        linux = {
          url = "build-tools_r18.1-linux.zip";
          sha1 = "f314a0599e51397f0886fe888b50dd98f2f050d8";
        };
        darwin = {
          url = "build-tools_r18.1-macosx.zip";
          sha1 = "16ddb299b8b43063e5bb3387ec17147c5053dfd8";
        };
        windows = {
          url = "build-tools_r18.1-windows.zip";
          sha1 = "3a9810fc8559ab03c09378f07531e8cae2f1db30";
        };
      };
      displayName = "Android SDK Build-Tools 18.1";
    };
    build-tools-18-1-1 = mkBuildTools {
      id = "build-tools;18.1.1";
      pname = "build-tools-18.1.1";
      version = "18.1.1";
      sources = {
        linux = {
          url = "build-tools_r18.1.1-linux.zip";
          sha1 = "68c9acbfc0cec2d51b19efaed39831a17055d998";
        };
        darwin = {
          url = "build-tools_r18.1.1-macosx.zip";
          sha1 = "a9d9d37f6ddf859e57abc78802a77aaa166e48d4";
        };
        windows = {
          url = "build-tools_r18.1.1-windows.zip";
          sha1 = "c4605066e2f851387ea70bc1442b1968bd7b4a15";
        };
      };
      displayName = "Android SDK Build-Tools 18.1.1";
    };
    build-tools-19-0-0 = mkBuildTools {
      id = "build-tools;19.0.0";
      pname = "build-tools-19.0.0";
      version = "19";
      sources = {
        linux = {
          url = "build-tools_r19-linux.zip";
          sha1 = "55c1a6cf632e7d346f0002b275ec41fd3137fd83";
        };
        darwin = {
          url = "build-tools_r19-macosx.zip";
          sha1 = "86ec1c12db1bc446b7bcaefc5cc14eb361044e90";
        };
        windows = {
          url = "build-tools_r19-windows.zip";
          sha1 = "6edf505c20f5ece9c48fa0aff9a90488f9654d52";
        };
      };
      displayName = "Android SDK Build-Tools 19";
    };
    build-tools-19-0-1 = mkBuildTools {
      id = "build-tools;19.0.1";
      pname = "build-tools-19.0.1";
      version = "19.0.1";
      sources = {
        linux = {
          url = "build-tools_r19.0.1-linux.zip";
          sha1 = "18d2312dc4368858914213087f4e61445aca4517";
        };
        darwin = {
          url = "build-tools_r19.0.1-macosx.zip";
          sha1 = "efaf50fb19a3edb8d03efbff76f89a249ad2920b";
        };
        windows = {
          url = "build-tools_r19.0.1-windows.zip";
          sha1 = "5ef422bac5b28f4ced108319ed4a6bc7050a6234";
        };
      };
      displayName = "Android SDK Build-Tools 19.0.1";
    };
    build-tools-19-0-2 = mkBuildTools {
      id = "build-tools;19.0.2";
      pname = "build-tools-19.0.2";
      version = "19.0.2";
      sources = {
        linux = {
          url = "build-tools_r19.0.2-linux.zip";
          sha1 = "a03a6bdea0091aea32e1b35b90a7294c9f04e3dd";
        };
        darwin = {
          url = "build-tools_r19.0.2-macosx.zip";
          sha1 = "145bc43065d45f756d99d87329d899052b9a9288";
        };
        windows = {
          url = "build-tools_r19.0.2-windows.zip";
          sha1 = "af664672d0d709c9ae30937b1062317d3ade7f95";
        };
      };
      displayName = "Android SDK Build-Tools 19.0.2";
    };
    build-tools-19-0-3 = mkBuildTools {
      id = "build-tools;19.0.3";
      pname = "build-tools-19.0.3";
      version = "19.0.3";
      sources = {
        linux = {
          url = "build-tools_r19.0.3-linux.zip";
          sha1 = "c2d6055478e9d2d4fba476ee85f99181ddd1160c";
        };
        darwin = {
          url = "build-tools_r19.0.3-macosx.zip";
          sha1 = "651cf8754373b2d52e7f6aab2c52eabffe4e9ea4";
        };
        windows = {
          url = "build-tools_r19.0.3-windows.zip";
          sha1 = "cb46b433b67a0a6910ff00db84be8b527ea3102f";
        };
      };
      displayName = "Android SDK Build-Tools 19.0.3";
    };
    build-tools-19-1-0 = mkBuildTools {
      id = "build-tools;19.1.0";
      pname = "build-tools-19.1.0";
      version = "19.1";
      sources = {
        linux = {
          url = "build-tools_r19.1-linux.zip";
          sha1 = "1ff20ac15fa47a75d00346ec12f180d531b3ca89";
        };
        darwin = {
          url = "build-tools_r19.1-macosx.zip";
          sha1 = "0d11aae3417de1efb4b9a0e0a7855904a61bcec1";
        };
        windows = {
          url = "build-tools_r19.1-windows.zip";
          sha1 = "13b367fbdbff8132cb4356f716e8dc8a8df745c5";
        };
      };
      displayName = "Android SDK Build-Tools 19.1";
    };
    build-tools-20-0-0 = mkBuildTools {
      id = "build-tools;20.0.0";
      pname = "build-tools-20.0.0";
      version = "20";
      sources = {
        linux = {
          url = "build-tools_r20-linux.zip";
          sha1 = "b688905526a5584d1327a662d871a635ff502758";
        };
        darwin = {
          url = "build-tools_r20-macosx.zip";
          sha1 = "1240f629411c108a714c4ddd756937c7fab93f83";
        };
        windows = {
          url = "build-tools_r20-windows.zip";
          sha1 = "cf20720e452b642d5eb59dabe05c0c729b36ec75";
        };
      };
      displayName = "Android SDK Build-Tools 20";
    };
    build-tools-21-0-0 = mkBuildTools {
      id = "build-tools;21.0.0";
      pname = "build-tools-21.0.0";
      version = "21";
      sources = {
        linux = {
          url = "build-tools_r21-linux.zip";
          sha1 = "4933328fdeecbd554a29528f254f4993468e1cf4";
        };
        darwin = {
          url = "build-tools_r21-macosx.zip";
          sha1 = "9bef7989b51436bd4e5114d8a0330359f077cbfa";
        };
        windows = {
          url = "build-tools_r21-windows.zip";
          sha1 = "5bc8fd399bc0135a9bc91eec78ddc5af4f54bf32";
        };
      };
      displayName = "Android SDK Build-Tools 21";
    };
    build-tools-21-0-1 = mkBuildTools {
      id = "build-tools;21.0.1";
      pname = "build-tools-21.0.1";
      version = "21.0.1";
      sources = {
        linux = {
          url = "build-tools_r21.0.1-linux.zip";
          sha1 = "e573069eea3e5255e7a65bedeb767f4fd0a5f49a";
        };
        darwin = {
          url = "build-tools_r21.0.1-macosx.zip";
          sha1 = "b60c8f9b810c980abafa04896706f3911be1ade7";
        };
        windows = {
          url = "build-tools_r21.0.1-windows.zip";
          sha1 = "d68e7e6fd7a48c8759aa41d713c9d4f0e4c1c1df";
        };
      };
      displayName = "Android SDK Build-Tools 21.0.1";
    };
    build-tools-21-0-2 = mkBuildTools {
      id = "build-tools;21.0.2";
      pname = "build-tools-21.0.2";
      version = "21.0.2";
      sources = {
        linux = {
          url = "build-tools_r21.0.2-linux.zip";
          sha1 = "e1236ab8897b62b57414adcf04c132567b2612a5";
        };
        darwin = {
          url = "build-tools_r21.0.2-macosx.zip";
          sha1 = "f17471c154058f3734729ef3cc363399b1cd3de1";
        };
        windows = {
          url = "build-tools_r21.0.2-windows.zip";
          sha1 = "37496141b23cbe633167927b7abe6e22d9f1a1c1";
        };
      };
      displayName = "Android SDK Build-Tools 21.0.2";
    };
    build-tools-21-1-0 = mkBuildTools {
      id = "build-tools;21.1.0";
      pname = "build-tools-21.1.0";
      version = "21.1";
      sources = {
        linux = {
          url = "build-tools_r21.1-linux.zip";
          sha1 = "b7455e543784d52a8925f960bc880493ed1478cb";
        };
        darwin = {
          url = "build-tools_r21.1-macosx.zip";
          sha1 = "df619356c2359aa5eacdd48699d15b335d9bd246";
        };
        windows = {
          url = "build-tools_r21.1-windows.zip";
          sha1 = "c79d63ac6b713a1e326ad4dae43f2ee76708a2f4";
        };
      };
      displayName = "Android SDK Build-Tools 21.1";
    };
    build-tools-21-1-1 = mkBuildTools {
      id = "build-tools;21.1.1";
      pname = "build-tools-21.1.1";
      version = "21.1.1";
      sources = {
        linux = {
          url = "build-tools_r21.1.1-linux.zip";
          sha1 = "1c712ee3a1ba5a8b0548f9c32f17d4a0ddfd727d";
        };
        darwin = {
          url = "build-tools_r21.1.1-macosx.zip";
          sha1 = "836a146eab0504aa9387a5132e986fe7c7381571";
        };
        windows = {
          url = "build-tools_r21.1.1-windows.zip";
          sha1 = "53fc4201237f899d5cd92f0b76ad41fb89da188b";
        };
      };
      displayName = "Android SDK Build-Tools 21.1.1";
    };
    build-tools-21-1-2 = mkBuildTools {
      id = "build-tools;21.1.2";
      pname = "build-tools-21.1.2";
      version = "21.1.2";
      sources = {
        linux = {
          url = "build-tools_r21.1.2-linux.zip";
          sha1 = "5e35259843bf2926113a38368b08458735479658";
        };
        darwin = {
          url = "build-tools_r21.1.2-macosx.zip";
          sha1 = "e7c906b4ba0eea93b32ba36c610dbd6b204bff48";
        };
        windows = {
          url = "build-tools_r21.1.2-windows.zip";
          sha1 = "1d944759c47f60e634d2b8a1f3a4259be2f8d652";
        };
      };
      displayName = "Android SDK Build-Tools 21.1.2";
    };
    build-tools-22-0-0 = mkBuildTools {
      id = "build-tools;22.0.0";
      pname = "build-tools-22.0.0";
      version = "22";
      sources = {
        linux = {
          url = "build-tools_r22-linux.zip";
          sha1 = "a8a1619dd090e44fac957bce6842e62abf87965b";
        };
        darwin = {
          url = "build-tools_r22-macosx.zip";
          sha1 = "af95429b24088d704bc5db9bd606e34ac1b82c0d";
        };
        windows = {
          url = "build-tools_r22-windows.zip";
          sha1 = "08fcca41e81b172bd9f570963b90d3a84929e043";
        };
      };
      displayName = "Android SDK Build-Tools 22";
    };
    build-tools-22-0-1 = mkBuildTools {
      id = "build-tools;22.0.1";
      pname = "build-tools-22.0.1";
      version = "22.0.1";
      sources = {
        linux = {
          url = "build-tools_r22.0.1-linux.zip";
          sha1 = "da8b9c5c3ede39298e6cf0283c000c2ee9029646";
        };
        darwin = {
          url = "build-tools_r22.0.1-macosx.zip";
          sha1 = "53dad7f608e01d53b17176ba11165acbfccc5bbf";
        };
        windows = {
          url = "build-tools_r22.0.1-windows.zip";
          sha1 = "61d8cbe069d9e0a57872a83e5e5abe164b7d52cf";
        };
      };
      displayName = "Android SDK Build-Tools 22.0.1";
    };
    build-tools-23-0-0 = mkBuildTools {
      id = "build-tools;23.0.0";
      pname = "build-tools-23.0.0";
      version = "23";
      sources = {
        linux = {
          url = "build-tools_r23-linux.zip";
          sha1 = "c1d6209212b01469f80fa804e0c1d39a06bc9060";
        };
        darwin = {
          url = "build-tools_r23-macosx.zip";
          sha1 = "90ba6e716f7703a236cd44b2e71c5ff430855a03";
        };
        windows = {
          url = "build-tools_r23-windows.zip";
          sha1 = "3874948f35f2f8946597679cc6e9151449f23b5d";
        };
      };
      displayName = "Android SDK Build-Tools 23";
    };
    build-tools-23-0-1 = mkBuildTools {
      id = "build-tools;23.0.1";
      pname = "build-tools-23.0.1";
      version = "23.0.1";
      sources = {
        linux = {
          url = "build-tools_r23.0.1-linux.zip";
          sha1 = "b6ba7c399d5fa487d95289d8832e4ad943aed556";
        };
        darwin = {
          url = "build-tools_r23.0.1-macosx.zip";
          sha1 = "d96ec1522721e9a179ae2c591c99f75d31d39718";
        };
        windows = {
          url = "build-tools_r23.0.1-windows.zip";
          sha1 = "cc1d37231d228f7a6f130e1f8d8c940052f0f8ab";
        };
      };
      displayName = "Android SDK Build-Tools 23.0.1";
    };
    build-tools-23-0-2 = mkBuildTools {
      id = "build-tools;23.0.2";
      pname = "build-tools-23.0.2";
      version = "23.0.2";
      sources = {
        linux = {
          url = "build-tools_r23.0.2-linux.zip";
          sha1 = "8a9f2b37f6fcf7a9fa784dc21aeaeb41bbb9f2c3";
        };
        darwin = {
          url = "build-tools_r23.0.2-macosx.zip";
          sha1 = "482c4cbceef8ff58aefd92d8155a38610158fdaf";
        };
        windows = {
          url = "build-tools_r23.0.2-windows.zip";
          sha1 = "fc3a92c744d3ba0a16ccb5d2b41eea5974ce0a96";
        };
      };
      displayName = "Android SDK Build-Tools 23.0.2";
    };
    build-tools-23-0-3 = mkBuildTools {
      id = "build-tools;23.0.3";
      pname = "build-tools-23.0.3";
      version = "23.0.3";
      sources = {
        linux = {
          url = "build-tools_r23.0.3-linux.zip";
          sha1 = "368f2600feac7e9b511b82f53d1f2240ae4a91a3";
        };
        darwin = {
          url = "build-tools_r23.0.3-macosx.zip";
          sha1 = "fbc98cd303fd15a31d472de6c03bd707829f00b0";
        };
        windows = {
          url = "build-tools_r23.0.3-windows.zip";
          sha1 = "c6d8266c6a3243c8f1e41b786c0e3cee4c781263";
        };
      };
      displayName = "Android SDK Build-Tools 23.0.3";
    };
    build-tools-24-0-0 = mkBuildTools {
      id = "build-tools;24.0.0";
      pname = "build-tools-24.0.0";
      version = "24";
      sources = {
        linux = {
          url = "build-tools_r24-linux.zip";
          sha1 = "c6271c4d78a5612ea6c7150688bcd5b7313de8d1";
        };
        darwin = {
          url = "build-tools_r24-macosx.zip";
          sha1 = "97fc4ed442f23989cc488d02c1d1de9bdde241de";
        };
        windows = {
          url = "build-tools_r24-windows.zip";
          sha1 = "dc61b9e5b451a0c3ec42ae2b1ce27c4d3c8da9f7";
        };
      };
      displayName = "Android SDK Build-Tools 24";
    };
    build-tools-24-0-1 = mkBuildTools {
      id = "build-tools;24.0.1";
      pname = "build-tools-24.0.1";
      version = "24.0.1";
      sources = {
        linux = {
          url = "build-tools_r24.0.1-linux.zip";
          sha1 = "84f18c392919a074fcbb9b1d967984e6b2fef8b4";
        };
        darwin = {
          url = "build-tools_r24.0.1-macosx.zip";
          sha1 = "5c6457fcdfa07724fb086d8ff4e8316fc0742848";
        };
        windows = {
          url = "build-tools_r24.0.1-windows.zip";
          sha1 = "ac4a7cea42c3ef74d7fbf1b992fad311c550034e";
        };
      };
      displayName = "Android SDK Build-Tools 24.0.1";
    };
    build-tools-24-0-2 = mkBuildTools {
      id = "build-tools;24.0.2";
      pname = "build-tools-24.0.2";
      version = "24.0.2";
      sources = {
        linux = {
          url = "build-tools_r24.0.2-linux.zip";
          sha1 = "f199a7a788c3fefbed102eea34d6007737b803cf";
        };
        darwin = {
          url = "build-tools_r24.0.2-macosx.zip";
          sha1 = "8bb8fc575477491d5957de743089df412de55cda";
        };
        windows = {
          url = "build-tools_r24.0.2-windows.zip";
          sha1 = "09586a1f1c39bcfa7db5205c9a07837247deb67e";
        };
      };
      displayName = "Android SDK Build-Tools 24.0.2";
    };
    build-tools-24-0-3 = mkBuildTools {
      id = "build-tools;24.0.3";
      pname = "build-tools-24.0.3";
      version = "24.0.3";
      sources = {
        linux = {
          url = "build-tools_r24.0.3-linux.zip";
          sha1 = "9e8cc49d66e03fa1a8ecc1ac3e58f1324f5da304";
        };
        darwin = {
          url = "build-tools_r24.0.3-macosx.zip";
          sha1 = "a01c15f1b105c34595681075e1895d58b3fff48c";
        };
        windows = {
          url = "build-tools_r24.0.3-windows.zip";
          sha1 = "8b960d693fd4163caeb8dc5f5f5f80b10987089c";
        };
      };
      displayName = "Android SDK Build-Tools 24.0.3";
    };
    build-tools-25-0-0 = mkBuildTools {
      id = "build-tools;25.0.0";
      pname = "build-tools-25.0.0";
      version = "25";
      sources = {
        linux = {
          url = "build-tools_r25-linux.zip";
          sha1 = "f2bbda60403e75cabd0f238598c3b4dfca56ea44";
        };
        darwin = {
          url = "build-tools_r25-macosx.zip";
          sha1 = "273c5c29a65cbed00e44f3aa470bbd7dce556606";
        };
        windows = {
          url = "build-tools_r25-windows.zip";
          sha1 = "f9258f2308ff8b62cfc4513d40cb961612d07b6a";
        };
      };
      displayName = "Android SDK Build-Tools 25";
    };
    build-tools-25-0-1 = mkBuildTools {
      id = "build-tools;25.0.1";
      pname = "build-tools-25.0.1";
      version = "25.0.1";
      sources = {
        linux = {
          url = "build-tools_r25.0.1-linux.zip";
          sha1 = "ff063d252ab750d339f5947d06ff782836f22bac";
        };
        darwin = {
          url = "build-tools_r25.0.1-macosx.zip";
          sha1 = "7bf7f22d7d48ef20b6ab0e3d7a2912e5c088340f";
        };
        windows = {
          url = "build-tools_r25.0.1-windows.zip";
          sha1 = "c6c61393565ccf46349e7f44511e5db7c1c6169d";
        };
      };
      displayName = "Android SDK Build-Tools 25.0.1";
    };
    build-tools-25-0-2 = mkBuildTools {
      id = "build-tools;25.0.2";
      pname = "build-tools-25.0.2";
      version = "25.0.2";
      sources = {
        linux = {
          url = "build-tools_r25.0.2-linux.zip";
          sha1 = "ff953c0177e317618fda40516f3e9d95fd43c7ae";
        };
        darwin = {
          url = "build-tools_r25.0.2-macosx.zip";
          sha1 = "12a5204bb3b6e39437535469fde7ddf42da46b16";
        };
        windows = {
          url = "build-tools_r25.0.2-windows.zip";
          sha1 = "2fee3c0704d6ecc480570450d8b8069b2c4a2dd4";
        };
      };
      displayName = "Android SDK Build-Tools 25.0.2";
    };
    build-tools-25-0-3 = mkBuildTools {
      id = "build-tools;25.0.3";
      pname = "build-tools-25.0.3";
      version = "25.0.3";
      sources = {
        linux = {
          url = "build-tools_r25.0.3-linux.zip";
          sha1 = "db95f3a0ae376534d4d69f4cdb6fad20649f3509";
        };
        darwin = {
          url = "build-tools_r25.0.3-macosx.zip";
          sha1 = "160d2fefb5ce68e443427fc30a793a703b63e26e";
        };
        windows = {
          url = "build-tools_r25.0.3-windows.zip";
          sha1 = "1edcb109ae5133aebfed573cf0bc84e0c353c28d";
        };
      };
      displayName = "Android SDK Build-Tools 25.0.3";
    };
    build-tools-26-0-0 = mkBuildTools {
      id = "build-tools;26.0.0";
      pname = "build-tools-26.0.0";
      version = "26";
      sources = {
        linux = {
          url = "build-tools_r26-linux.zip";
          sha1 = "1cbe72929876f8a872ab1f1b1040a9f720261f59";
        };
        darwin = {
          url = "build-tools_r26-macosx.zip";
          sha1 = "d01a1aeca03747245f1f5936b3cb01759c66d086";
        };
        windows = {
          url = "build-tools_r26-windows.zip";
          sha1 = "896ebd31117c09db220f7a3116cc0e5121c78b9d";
        };
      };
      displayName = "Android SDK Build-Tools 26";
    };
    build-tools-26-0-1 = mkBuildTools {
      id = "build-tools;26.0.1";
      pname = "build-tools-26.0.1";
      version = "26.0.1";
      sources = {
        linux = {
          url = "build-tools_r26.0.1-linux.zip";
          sha1 = "5378c2c78091b414d0eac40a6bd37f2faa31a365";
        };
        darwin = {
          url = "build-tools_r26.0.1-macosx.zip";
          sha1 = "cbde59de198916b390777dd0227921bfa2120832";
        };
        windows = {
          url = "build-tools_r26.0.1-windows.zip";
          sha1 = "02494c80ffbe65bfff0aaa7463c9692693327b7d";
        };
      };
      displayName = "Android SDK Build-Tools 26.0.1";
    };
    build-tools-26-0-2 = mkBuildTools {
      id = "build-tools;26.0.2";
      pname = "build-tools-26.0.2";
      version = "26.0.2";
      sources = {
        linux = {
          url = "build-tools_r26.0.2-linux.zip";
          sha1 = "5b2b7b66c7bf2151f2af183b5b50a17808850592";
        };
        darwin = {
          url = "build-tools_r26.0.2-macosx.zip";
          sha1 = "d9ed7c7f149ce38be5dc08979aea8acec1459ca0";
        };
        windows = {
          url = "build-tools_r26.0.2-windows.zip";
          sha1 = "39ca02d3faa49859cd9d1bc0adc2f331017b699b";
        };
      };
      displayName = "Android SDK Build-Tools 26.0.2";
    };
    build-tools-26-0-3 = mkBuildTools {
      id = "build-tools;26.0.3";
      pname = "build-tools-26.0.3";
      version = "26.0.3";
      sources = {
        linux = {
          url = "build-tools_r26.0.3-linux.zip";
          sha1 = "8a2e6c1bcd845844523a68aa17e5442f0dce328c";
        };
        darwin = {
          url = "build-tools_r26.0.3-macosx.zip";
          sha1 = "5bb90ed935d99e5bc90686f43b852e68c5ad40df";
        };
        windows = {
          url = "build-tools_r26.0.3-windows.zip";
          sha1 = "460e511a9616b4661cc8dba0102d9d990ae60160";
        };
      };
      displayName = "Android SDK Build-Tools 26.0.3";
    };
    build-tools-27-0-0 = mkBuildTools {
      id = "build-tools;27.0.0";
      pname = "build-tools-27.0.0";
      version = "27";
      sources = {
        linux = {
          url = "build-tools_r27-linux.zip";
          sha1 = "28542332ba97cf4a08c3eddfcf5edd70e3cf1260";
        };
        darwin = {
          url = "build-tools_r27-macosx.zip";
          sha1 = "fb4e8d7e6b8d29a77090e34024077a80458d5ae1";
        };
        windows = {
          url = "build-tools_r27-windows.zip";
          sha1 = "4f1df22a6d99261d2160d624b81445da0a027dbe";
        };
      };
      displayName = "Android SDK Build-Tools 27";
    };
    build-tools-27-0-1 = mkBuildTools {
      id = "build-tools;27.0.1";
      pname = "build-tools-27.0.1";
      version = "27.0.1";
      sources = {
        linux = {
          url = "build-tools_r27.0.1-linux.zip";
          sha1 = "7f4eedb1077ef948b848040dcd15de9e8a759f4a";
        };
        darwin = {
          url = "build-tools_r27.0.1-macosx.zip";
          sha1 = "1edd07bfdbadd95652d093040e16d858f7489594";
        };
        windows = {
          url = "build-tools_r27.0.1-windows.zip";
          sha1 = "18109db020c6d088d0157d1df201d31bc6970875";
        };
      };
      displayName = "Android SDK Build-Tools 27.0.1";
    };
    build-tools-27-0-2 = mkBuildTools {
      id = "build-tools;27.0.2";
      pname = "build-tools-27.0.2";
      version = "27.0.2";
      sources = {
        linux = {
          url = "build-tools_r27.0.2-linux.zip";
          sha1 = "b687ddf6be84f11607871138aad32cf857d0b837";
        };
        darwin = {
          url = "build-tools_r27.0.2-macosx.zip";
          sha1 = "6d5d9cf2a47877f273f4b742b19e712a051a31be";
        };
        windows = {
          url = "build-tools_r27.0.2-windows.zip";
          sha1 = "b80466c13b75e3ebf3c546964f40775db5898b2a";
        };
      };
      displayName = "Android SDK Build-Tools 27.0.2";
    };
    build-tools-27-0-3 = mkBuildTools {
      id = "build-tools;27.0.3";
      pname = "build-tools-27.0.3";
      version = "27.0.3";
      sources = {
        linux = {
          url = "build-tools_r27.0.3-linux.zip";
          sha1 = "d85e7a6320eddffe7eeace3437605079dac938ca";
        };
        darwin = {
          url = "build-tools_r27.0.3-macosx.zip";
          sha1 = "61d9fb18790c68d66ff73bf1e7ad56bc1f1eef2d";
        };
        windows = {
          url = "build-tools_r27.0.3-windows.zip";
          sha1 = "0df61e11713a2838d2cc9a911219dddf5e6a2749";
        };
      };
      displayName = "Android SDK Build-Tools 27.0.3";
    };
    build-tools-28-0-0 = mkBuildTools {
      id = "build-tools;28.0.0";
      pname = "build-tools-28.0.0";
      version = "28";
      sources = {
        linux = {
          url = "build-tools_r28-linux.zip";
          sha1 = "d9f8a754d833ccd334f56fcc6089c5925cd82abb";
        };
        darwin = {
          url = "build-tools_r28-macosx.zip";
          sha1 = "72088d32d1d82cc3c2cf7cf6618b6130c0c84ade";
        };
        windows = {
          url = "build-tools_r28-windows.zip";
          sha1 = "d4b0638a877ed570e07876264e69fdbd86409610";
        };
      };
      displayName = "Android SDK Build-Tools 28";
    };
    build-tools-28-0-0-rc1 = mkBuildTools {
      id = "build-tools;28.0.0-rc1";
      pname = "build-tools-28.0.0-rc1";
      version = "28-rc1";
      sources = {
        linux = {
          url = "build-tools_r28-rc1-linux.zip";
          sha1 = "1601977fae25fd478bcfaa0481ca5ea3c609d840";
        };
        darwin = {
          url = "build-tools_r28-rc1-macosx.zip";
          sha1 = "2c77821967a2330b7b227072d0b1c02ef19fe2fc";
        };
        windows = {
          url = "build-tools_r28-rc1-windows.zip";
          sha1 = "fbf46c33d1268f6532911707b2a05033fd5c5b41";
        };
      };
      displayName = "Android SDK Build-Tools 28-rc1";
    };
    build-tools-28-0-0-rc2 = mkBuildTools {
      id = "build-tools;28.0.0-rc2";
      pname = "build-tools-28.0.0-rc2";
      version = "28-rc2";
      sources = {
        linux = {
          url = "build-tools_r28-rc2-linux.zip";
          sha1 = "efe9c0dde0646a07544c864276390ca6e96b24dc";
        };
        darwin = {
          url = "build-tools_r28-rc2-macosx.zip";
          sha1 = "0d0314b353589feb10e528b44c5a685b6658d797";
        };
        windows = {
          url = "build-tools_r28-rc2-windows.zip";
          sha1 = "a94bfb52b4ec74b95c116236c3e382e923cad6c4";
        };
      };
      displayName = "Android SDK Build-Tools 28-rc2";
    };
    build-tools-28-0-1 = mkBuildTools {
      id = "build-tools;28.0.1";
      pname = "build-tools-28.0.1";
      version = "28.0.1";
      sources = {
        linux = {
          url = "build-tools_r28.0.1-linux.zip";
          sha1 = "ee70dfa1fccb58b37cebc9544830511f36a137a0";
        };
        darwin = {
          url = "build-tools_r28.0.1-macosx.zip";
          sha1 = "aeef42ad953f1630dd6f5d71eefdc0b825211462";
        };
        windows = {
          url = "build-tools_r28.0.1-windows.zip";
          sha1 = "29c6342835734be25b9e458ab3fad5750ad6a355";
        };
      };
      displayName = "Android SDK Build-Tools 28.0.1";
    };
    build-tools-28-0-2 = mkBuildTools {
      id = "build-tools;28.0.2";
      pname = "build-tools-28.0.2";
      version = "28.0.2";
      sources = {
        linux = {
          url = "build-tools_r28.0.2-linux.zip";
          sha1 = "b4492209810a3fd48deaa982f9852fef12433d55";
        };
        darwin = {
          url = "build-tools_r28.0.2-macosx.zip";
          sha1 = "c10dd5a7825578622fb362a8a34f76eb3ba0c0a9";
        };
        windows = {
          url = "build-tools_r28.0.2-windows.zip";
          sha1 = "e9c570c568a0c2a32e88ee3204279019ebefd949";
        };
      };
      displayName = "Android SDK Build-Tools 28.0.2";
    };
    build-tools-28-0-3 = mkBuildTools {
      id = "build-tools;28.0.3";
      pname = "build-tools-28.0.3";
      version = "28.0.3";
      sources = {
        linux = {
          url = "build-tools_r28.0.3-linux.zip";
          sha1 = "ea6f2f7103cd9da9ff0bdf6e37fbbba548fa4165";
        };
        darwin = {
          url = "build-tools_r28.0.3-macosx.zip";
          sha1 = "f8c333a2991b1ab05a671bc6248b78e00edcd83a";
        };
        windows = {
          url = "build-tools_r28.0.3-windows.zip";
          sha1 = "05bd35bb48d11c848da2b393c6f864eb609aacba";
        };
      };
      displayName = "Android SDK Build-Tools 28.0.3";
    };
    build-tools-29-0-0 = mkBuildTools {
      id = "build-tools;29.0.0";
      pname = "build-tools-29.0.0";
      version = "29";
      sources = {
        linux = {
          url = "build-tools_r29-linux.zip";
          sha1 = "ad314caf1802209c4b00a5f3517af5ceb0d48eae";
        };
        darwin = {
          url = "build-tools_r29-macosx.zip";
          sha1 = "35dc6bc7a53bd9d206847e72f02cab21cfdaa869";
        };
        windows = {
          url = "build-tools_r29-windows.zip";
          sha1 = "1799f7f975416098e5a5bf280eb97c8f77cf7f79";
        };
      };
      displayName = "Android SDK Build-Tools 29";
    };
    build-tools-29-0-0-rc1 = mkBuildTools {
      id = "build-tools;29.0.0-rc1";
      pname = "build-tools-29.0.0-rc1";
      version = "29-rc1";
      sources = {
        linux = {
          url = "build-tools_r29-rc1-linux.zip";
          sha1 = "1c897f5885ac5468613e40e1ea598c21c05d345d";
        };
        darwin = {
          url = "build-tools_r29-rc1-macosx.zip";
          sha1 = "f066c0d9ea2f0d8a0a9cc7b2ca0a467a570ab034";
        };
        windows = {
          url = "build-tools_r29-rc1-windows.zip";
          sha1 = "8887ee791a143f92694a0908130354142a903b17";
        };
      };
      displayName = "Android SDK Build-Tools 29-rc1";
    };
    build-tools-29-0-0-rc2 = mkBuildTools {
      id = "build-tools;29.0.0-rc2";
      pname = "build-tools-29.0.0-rc2";
      version = "29-rc2";
      sources = {
        linux = {
          url = "build-tools_r29-rc2-linux.zip";
          sha1 = "b4b41d429c35b42db07b6c65d4aa998ba8c4093c";
        };
        darwin = {
          url = "build-tools_r29-rc2-macosx.zip";
          sha1 = "7a960367999169ccac5dbc60817e5f1725c4c738";
        };
        windows = {
          url = "build-tools_r29-rc2-windows.zip";
          sha1 = "2de2a3e290cae4ce35e82c8a5abed49b1cdd24e3";
        };
      };
      displayName = "Android SDK Build-Tools 29-rc2";
    };
    build-tools-29-0-0-rc3 = mkBuildTools {
      id = "build-tools;29.0.0-rc3";
      pname = "build-tools-29.0.0-rc3";
      version = "29-rc3";
      sources = {
        linux = {
          url = "build-tools_r29-rc3-linux.zip";
          sha1 = "8b7177f198e8b92da8f9537aaf859f6edf222b01";
        };
        darwin = {
          url = "build-tools_r29-rc3-macosx.zip";
          sha1 = "643e8d76625f6e2cfcd5494e50bae5e14725ec0c";
        };
        windows = {
          url = "build-tools_r29-rc3-windows.zip";
          sha1 = "6abce2ebfecf3580afd3129520999f95691a03df";
        };
      };
      displayName = "Android SDK Build-Tools 29-rc3";
    };
    build-tools-29-0-1 = mkBuildTools {
      id = "build-tools;29.0.1";
      pname = "build-tools-29.0.1";
      version = "29.0.1";
      sources = {
        linux = {
          url = "build-tools_r29.0.1-linux.zip";
          sha1 = "fc209e5d91ab2daeac24345a5cb17261940547e4";
        };
        darwin = {
          url = "build-tools_r29.0.1-macosx.zip";
          sha1 = "46ae9b1d1e2a67241d7da9c2cd8eae42f24cc6cd";
        };
        windows = {
          url = "build-tools_r29.0.1-windows.zip";
          sha1 = "1c44e10d5f74e58c3e05bfc6f1631a59616059bc";
        };
      };
      displayName = "Android SDK Build-Tools 29.0.1";
    };
    build-tools-29-0-2 = mkBuildTools {
      id = "build-tools;29.0.2";
      pname = "build-tools-29.0.2";
      version = "29.0.2";
      sources = {
        linux = {
          url = "build-tools_r29.0.2-linux.zip";
          sha1 = "c0fc7e5c37ac96bfd0c611802e8ab36d0e71b398";
        };
        darwin = {
          url = "build-tools_r29.0.2-macosx.zip";
          sha1 = "f781d9e03d5c2debcf51fed3792ee7a9d066723f";
        };
        windows = {
          url = "build-tools_r29.0.2-windows.zip";
          sha1 = "595dc1730c844d892516d5f0e7894e992d19f63d";
        };
      };
      displayName = "Android SDK Build-Tools 29.0.2";
    };
    cmake-3-10-2-4988404 = mkPrebuilt {
      id = "cmake;3.10.2.4988404";
      pname = "cmake-3.10.2.4988404";
      version = "3.10.2";
      sources = {
        x86_64-darwin = {
          url = "cmake-3.10.2-darwin-x86_64.zip";
          sha1 = "f227a85cb53dcb927ac52a5a717f647c4a29bf3b";
        };
        x86_64-linux = {
          url = "cmake-3.10.2-linux-x86_64.zip";
          sha1 = "439e8799bf59f724f104bf62784b2985f1bfe561";
        };
        x86_64-windows = {
          url = "cmake-3.10.2-windows-x86_64.zip";
          sha1 = "0a75b9c5bf558dc31caad7241a44515064656486";
        };
      };
      displayName = "CMake 3.10.2.4988404";
    };
    cmake-3-6-4111459 = mkPrebuilt {
      id = "cmake;3.6.4111459";
      pname = "cmake-3.6.4111459";
      version = "3.6.4111459";
      sources = {
        x86_64-darwin = {
          url = "cmake-3.6.4111459-darwin-x86_64.zip";
          sha1 = "c9b02d630079783c6d67cb91488b622cfcd9765c";
        };
        x86_64-linux = {
          url = "cmake-3.6.4111459-linux-x86_64.zip";
          sha1 = "71c539b9c33f0943e9ad6251fea0b161c0b70782";
        };
        x86_64-windows = {
          url = "cmake-3.6.4111459-windows-x86_64.zip";
          sha1 = "4c4730dc3f399b2fa9ab701112d2c439368a59a5";
        };
      };
      displayName = "CMake 3.6.4111459";
    };
    docs = mkGeneric {
      id = "docs";
      pname = "docs";
      version = "1";
      sources = {
        all = {
          url = "docs-24_r01.zip";
          sha1 = "eef58238949ee9544876cb3e002f2d58e4ee7b5d";
        };
      };
      displayName = "Documentation for Android SDK";
    };
    emulator = mkEmulator {
      id = "emulator";
      pname = "emulator";
      version = "29.2.1";
      sources = {
        x86_64-darwin = {
          url = "emulator-darwin-5889189.zip";
          sha1 = "ccee1a25339c8f5c059abf7297625a6e91fe137c";
        };
        x86_64-linux = {
          url = "emulator-linux-5889189.zip";
          sha1 = "ebbaff0512ef72ba69d83fbc700c58f25e9edc9d";
        };
        x86_64-windows = {
          url = "emulator-windows-5889189.zip";
          sha1 = "d8d418642d2837af6037b84cf36baaf8073837ae";
        };
      };
      displayName = "Android Emulator";
    };
    lldb-2-0 = mkPrebuilt {
      id = "lldb;2.0";
      pname = "lldb-2.0";
      version = "2.0.2558144";
      sources = {
        x86_64-darwin = {
          url = "lldb-2.0.2558144-darwin-x86_64.zip";
          sha1 = "d92e2f4c8284413eed4f27986e62b167d947033c";
        };
        x86_64-linux = {
          url = "lldb-2.0.2558144-linux-x86_64.zip";
          sha1 = "e7060d9b2ba58b28fd7b1a0ea85a151c8371a326";
        };
        i686-windows = {
          url = "lldb-2.0.2558144-windows-x86.zip";
          sha1 = "86fd4676dfb587efe8e84face780d6e8241c0b3a";
        };
        x86_64-windows = {
          url = "lldb-2.0.2558144-windows-x86_64.zip";
          sha1 = "86fd4676dfb587efe8e84face780d6e8241c0b3a";
        };
      };
      displayName = "LLDB 2.0";
    };
    lldb-2-1 = mkPrebuilt {
      id = "lldb;2.1";
      pname = "lldb-2.1";
      version = "2.1.2852477";
      sources = {
        x86_64-darwin = {
          url = "lldb-2.1.2852477-darwin-x86_64.zip";
          sha1 = "d1e33880a53f1aa8c7e73534adef83a06f091185";
        };
        x86_64-linux = {
          url = "lldb-2.1.2852477-linux-x86_64.zip";
          sha1 = "eb9b96d320210fdfe82495b0597ad43e77f1c240";
        };
        i686-windows = {
          url = "lldb-2.1.2852477-windows-x86.zip";
          sha1 = "1d9c7d3db1e90587be15c9e79db6bd2881c65387";
        };
        x86_64-windows = {
          url = "lldb-2.1.2852477-windows-x86_64.zip";
          sha1 = "1d9c7d3db1e90587be15c9e79db6bd2881c65387";
        };
      };
      displayName = "LLDB 2.1";
    };
    lldb-2-2 = mkPrebuilt {
      id = "lldb;2.2";
      pname = "lldb-2.2";
      version = "2.2.3271982";
      sources = {
        x86_64-darwin = {
          url = "lldb-2.2.3271982-darwin-x86_64.zip";
          sha1 = "62089f4e35775e6cedb82d1fa377fdc1de898005";
        };
        x86_64-linux = {
          url = "lldb-2.2.3271982-linux-x86_64.zip";
          sha1 = "413649617d97dd9ef163528f64c0500e1b7c4113";
        };
        windows = {
          url = "lldb-2.2.3271982-windows.zip";
          sha1 = "7ee86628e6e25d84f2b4244efe587f2ca2e3af79";
        };
      };
      displayName = "LLDB 2.2";
    };
    lldb-2-3 = mkPrebuilt {
      id = "lldb;2.3";
      pname = "lldb-2.3";
      version = "2.3.3614996";
      sources = {
        x86_64-darwin = {
          url = "lldb-2.3.3614996-darwin-x86_64.zip";
          sha1 = "6b0df112c7b9fa41654497fde2fcce990c831e52";
        };
        x86_64-linux = {
          url = "lldb-2.3.3614996-linux-x86_64.zip";
          sha1 = "d7abe655650efe9f6989df31835fa3b3f95c2d13";
        };
        windows = {
          url = "lldb-2.3.3614996-windows.zip";
          sha1 = "f1ade0f54a6af82ef0cebde03ebf0bb12ae9767d";
        };
      };
      displayName = "LLDB 2.3";
    };
    lldb-3-0 = mkPrebuilt {
      id = "lldb;3.0";
      pname = "lldb-3.0";
      version = "3.0.4213617";
      sources = {
        x86_64-darwin = {
          url = "lldb-3.0.4213617-darwin-x86_64.zip";
          sha1 = "2492651690a215317b86c755cd4d584ec9838677";
        };
        x86_64-linux = {
          url = "lldb-3.0.4213617-linux-x86_64.zip";
          sha1 = "61d49b6a58953faa61546d631409af5f60d8d9db";
        };
        windows = {
          url = "lldb-3.0.4213617-windows.zip";
          sha1 = "3939e78a1a63e6d8006b4ef939007886d66cc3f6";
        };
      };
      displayName = "LLDB 3.0";
    };
    lldb-3-1 = mkPrebuilt {
      id = "lldb;3.1";
      pname = "lldb-3.1";
      version = "3.1.4508709";
      sources = {
        x86_64-darwin = {
          url = "lldb-3.1.4508709-darwin-x86_64.zip";
          sha1 = "2b37aa55b81a7e5b8a369febf1ac0bad6c7c5d58";
        };
        x86_64-linux = {
          url = "lldb-3.1.4508709-linux-x86_64.zip";
          sha1 = "462711c9ee94fec9ff8be5fa8180afec04d1af6f";
        };
        windows = {
          url = "lldb-3.1.4508709-windows.zip";
          sha1 = "8e54b7123084fa9e4e3b890626c5671b7552450f";
        };
      };
      displayName = "LLDB 3.1";
    };
    patcher.v4 = mkGeneric {
      id = "patcher;v4";
      pname = "patcher-v4";
      version = "1";
      sources = {
        all = {
          url = "3534162-studio.sdk-patcher.zip";
          sha1 = "046699c5e2716ae11d77e0bad814f7f33fab261e";
        };
      };
      displayName = "SDK Patch Applier v4";
    };
    platform-tools = mkPlatformTools {
      id = "platform-tools";
      pname = "platform-tools";
      version = "29.0.4";
      sources = {
        darwin = {
          url = "platform-tools_r29.0.4-darwin.zip";
          sha1 = "64a1e847c02ad404b3dbfd80487eefc97e6b3696";
        };
        linux = {
          url = "platform-tools_r29.0.4-linux.zip";
          sha1 = "a266af09893d9005d887e5f788ddb68f006ccd3e";
        };
        windows = {
          url = "platform-tools_r29.0.4-windows.zip";
          sha1 = "0b3a4a84436f2691f553ce9544bac34db20f00fa";
        };
      };
      displayName = "Android SDK Platform-Tools";
    };
    platforms.android-10 = mkGeneric {
      id = "platforms;android-10";
      pname = "platforms-android-10";
      version = "2";
      sources = {
        all = {
          url = "android-2.3.3_r02.zip";
          sha1 = "887e37783ec32f541ea33c2c649dda648e8e6fb3";
        };
      };
      displayName = "Android SDK Platform 10";
    };
    platforms.android-11 = mkGeneric {
      id = "platforms;android-11";
      pname = "platforms-android-11";
      version = "2";
      sources = {
        all = {
          url = "android-3.0_r02.zip";
          sha1 = "2c7d4bd13f276e76f6bbd87315fe27aba351dd37";
        };
      };
      displayName = "Android SDK Platform 11";
    };
    platforms.android-12 = mkGeneric {
      id = "platforms;android-12";
      pname = "platforms-android-12";
      version = "3";
      sources = {
        all = {
          url = "android-3.1_r03.zip";
          sha1 = "4a50a6679cd95bb68bb5fc032e754cd7c5e2b1bf";
        };
      };
      displayName = "Android SDK Platform 12";
    };
    platforms.android-13 = mkGeneric {
      id = "platforms;android-13";
      pname = "platforms-android-13";
      version = "1";
      sources = {
        all = {
          url = "android-3.2_r01.zip";
          sha1 = "6189a500a8c44ae73a439604363de93591163cd9";
        };
      };
      displayName = "Android SDK Platform 13";
    };
    platforms.android-14 = mkGeneric {
      id = "platforms;android-14";
      pname = "platforms-android-14";
      version = "4";
      sources = {
        all = {
          url = "android-14_r04.zip";
          sha1 = "d4f1d8fbca25225b5f0e7a0adf0d39c3d6e60b3c";
        };
      };
      displayName = "Android SDK Platform 14";
    };
    platforms.android-15 = mkGeneric {
      id = "platforms;android-15";
      pname = "platforms-android-15";
      version = "5";
      sources = {
        all = {
          url = "android-15_r05.zip";
          sha1 = "69ab4c443b37184b2883af1fd38cc20cbeffd0f3";
        };
      };
      displayName = "Android SDK Platform 15";
    };
    platforms.android-16 = mkGeneric {
      id = "platforms;android-16";
      pname = "platforms-android-16";
      version = "5";
      sources = {
        all = {
          url = "android-16_r05.zip";
          sha1 = "12a5ce6235a76bc30f62c26bda1b680e336abd07";
        };
      };
      displayName = "Android SDK Platform 16";
    };
    platforms.android-17 = mkGeneric {
      id = "platforms;android-17";
      pname = "platforms-android-17";
      version = "3";
      sources = {
        all = {
          url = "android-17_r03.zip";
          sha1 = "dbe14101c06e6cdb34e300393e64e64f8c92168a";
        };
      };
      displayName = "Android SDK Platform 17";
    };
    platforms.android-18 = mkGeneric {
      id = "platforms;android-18";
      pname = "platforms-android-18";
      version = "3";
      sources = {
        all = {
          url = "android-18_r03.zip";
          sha1 = "e6b09b3505754cbbeb4a5622008b907262ee91cb";
        };
      };
      displayName = "Android SDK Platform 18";
    };
    platforms.android-19 = mkGeneric {
      id = "platforms;android-19";
      pname = "platforms-android-19";
      version = "4";
      sources = {
        all = {
          url = "android-19_r04.zip";
          sha1 = "2ff20d89e68f2f5390981342e009db5a2d456aaa";
        };
      };
      displayName = "Android SDK Platform 19";
    };
    platforms.android-2 = mkGeneric {
      id = "platforms;android-2";
      pname = "platforms-android-2";
      version = "1";
      sources = {
        linux = {
          url = "android-1.1_r1-linux.zip";
          sha1 = "c054d25c9b4c6251fa49c2f9c54336998679d3fe";
        };
        darwin = {
          url = "android-1.1_r1-macosx.zip";
          sha1 = "e21dbcff45b7356657449ebb3c7e941be2bb5ebe";
        };
        windows = {
          url = "android-1.1_r1-windows.zip";
          sha1 = "a4060f29ed39fc929c302836d488998c53c3002e";
        };
      };
      displayName = "Android SDK Platform 2";
    };
    platforms.android-20 = mkGeneric {
      id = "platforms;android-20";
      pname = "platforms-android-20";
      version = "2";
      sources = {
        all = {
          url = "android-20_r02.zip";
          sha1 = "a9251f8a3f313ab05834a07a963000927637e01d";
        };
      };
      displayName = "Android SDK Platform 20";
    };
    platforms.android-21 = mkGeneric {
      id = "platforms;android-21";
      pname = "platforms-android-21";
      version = "2";
      sources = {
        all = {
          url = "android-21_r02.zip";
          sha1 = "53536556059bb29ae82f414fd2e14bc335a4eb4c";
        };
      };
      displayName = "Android SDK Platform 21";
    };
    platforms.android-22 = mkGeneric {
      id = "platforms;android-22";
      pname = "platforms-android-22";
      version = "2";
      sources = {
        all = {
          url = "android-22_r02.zip";
          sha1 = "5d1bd10fea962b216a0dece1247070164760a9fc";
        };
      };
      displayName = "Android SDK Platform 22";
    };
    platforms.android-23 = mkGeneric {
      id = "platforms;android-23";
      pname = "platforms-android-23";
      version = "3";
      sources = {
        all = {
          url = "platform-23_r03.zip";
          sha1 = "027fede3de6aa1649115bbd0bffff30ccd51c9a0";
        };
      };
      displayName = "Android SDK Platform 23";
    };
    platforms.android-24 = mkGeneric {
      id = "platforms;android-24";
      pname = "platforms-android-24";
      version = "2";
      sources = {
        all = {
          url = "platform-24_r02.zip";
          sha1 = "8912da3d4bfe7a9f28f0e5ce92d3a8dc96342aee";
        };
      };
      displayName = "Android SDK Platform 24";
    };
    platforms.android-25 = mkGeneric {
      id = "platforms;android-25";
      pname = "platforms-android-25";
      version = "3";
      sources = {
        all = {
          url = "platform-25_r03.zip";
          sha1 = "00c2c5765e8988504be10a1eb66ed71fcdbd7fe8";
        };
      };
      displayName = "Android SDK Platform 25";
    };
    platforms.android-26 = mkGeneric {
      id = "platforms;android-26";
      pname = "platforms-android-26";
      version = "2";
      sources = {
        all = {
          url = "platform-26_r02.zip";
          sha1 = "e4ae5d7aa557a3c827135838ee400da8443ac4ef";
        };
      };
      displayName = "Android SDK Platform 26";
    };
    platforms.android-27 = mkGeneric {
      id = "platforms;android-27";
      pname = "platforms-android-27";
      version = "3";
      sources = {
        all = {
          url = "platform-27_r03.zip";
          sha1 = "35f747e7e70b2d16e0e4246876be28d15ea1c353";
        };
      };
      displayName = "Android SDK Platform 27";
    };
    platforms.android-28 = mkGeneric {
      id = "platforms;android-28";
      pname = "platforms-android-28";
      version = "6";
      sources = {
        all = {
          url = "platform-28_r06.zip";
          sha1 = "9a4e52b1d55bd2e24216b150aafae2503d3efba6";
        };
      };
      displayName = "Android SDK Platform 28";
    };
    platforms.android-29 = mkGeneric {
      id = "platforms;android-29";
      pname = "platforms-android-29";
      version = "3";
      sources = {
        all = {
          url = "platform-29_r03.zip";
          sha1 = "670e2e104333dae90e16ea3b615f0b63da5883ae";
        };
      };
      displayName = "Android SDK Platform 29";
    };
    platforms.android-3 = mkGeneric {
      id = "platforms;android-3";
      pname = "platforms-android-3";
      version = "4";
      sources = {
        linux = {
          url = "android-1.5_r04-linux.zip";
          sha1 = "5c134b7df5f4b8bd5b61ba93bdaebada8fa3468c";
        };
        darwin = {
          url = "android-1.5_r04-macosx.zip";
          sha1 = "d3a67c2369afa48b6c3c7624de5031c262018d1e";
        };
        windows = {
          url = "android-1.5_r04-windows.zip";
          sha1 = "5bb106d2e40d481edd337b0833093843e15fe49a";
        };
      };
      displayName = "Android SDK Platform 3";
    };
    platforms.android-4 = mkGeneric {
      id = "platforms;android-4";
      pname = "platforms-android-4";
      version = "3";
      sources = {
        linux = {
          url = "android-1.6_r03-linux.zip";
          sha1 = "483ed088e45bbdf3444baaf9250c8b02e5383cb0";
        };
        darwin = {
          url = "android-1.6_r03-macosx.zip";
          sha1 = "bdafad44f5df9f127979bdb21a1fdd87ee3cd625";
        };
        windows = {
          url = "android-1.6_r03-windows.zip";
          sha1 = "ce0b5e4ffaf12ca4fd07c2da71a8a1ab4a03dc22";
        };
      };
      displayName = "Android SDK Platform 4";
    };
    platforms.android-5 = mkGeneric {
      id = "platforms;android-5";
      pname = "platforms-android-5";
      version = "1";
      sources = {
        linux = {
          url = "android-2.0_r01-linux.zip";
          sha1 = "be9be6a99ca32875c96ec7f91160ca9fce7e3c7d";
        };
        darwin = {
          url = "android-2.0_r01-macosx.zip";
          sha1 = "2a866d0870dbba18e0503cd41e5fae988a21b314";
        };
        windows = {
          url = "android-2.0_r01-windows.zip";
          sha1 = "aeb623217ff88b87216d6eb7dbc846ed53f68f57";
        };
      };
      displayName = "Android SDK Platform 5";
    };
    platforms.android-6 = mkGeneric {
      id = "platforms;android-6";
      pname = "platforms-android-6";
      version = "1";
      sources = {
        linux = {
          url = "android-2.0.1_r01-linux.zip";
          sha1 = "ce2c971dce352aa28af06bda92a070116aa5ae1a";
        };
        darwin = {
          url = "android-2.0.1_r01-macosx.zip";
          sha1 = "c3096f80d75a6fc8cb38ef8a18aec920e53d42c0";
        };
        windows = {
          url = "android-2.0.1_r01-windows.zip";
          sha1 = "255781ebe4509d9707d0e77edda2815e2bc216e6";
        };
      };
      displayName = "Android SDK Platform 6";
    };
    platforms.android-7 = mkGeneric {
      id = "platforms;android-7";
      pname = "platforms-android-7";
      version = "3";
      sources = {
        all = {
          url = "android-2.1_r03.zip";
          sha1 = "5ce51b023ac19f8738500b1007a1da5de2349a1e";
        };
      };
      displayName = "Android SDK Platform 7";
    };
    platforms.android-8 = mkGeneric {
      id = "platforms;android-8";
      pname = "platforms-android-8";
      version = "3";
      sources = {
        all = {
          url = "android-2.2_r03.zip";
          sha1 = "231262c63eefdff8fd0386e9ccfefeb27a8f9202";
        };
      };
      displayName = "Android SDK Platform 8";
    };
    platforms.android-9 = mkGeneric {
      id = "platforms;android-9";
      pname = "platforms-android-9";
      version = "2";
      sources = {
        all = {
          url = "android-2.3.1_r02.zip";
          sha1 = "209f8a7a8b2cb093fce858b8b55fed3ba5206773";
        };
      };
      displayName = "Android SDK Platform 9";
    };
    sources.android-14 = mkGeneric {
      id = "sources;android-14";
      pname = "sources-android-14";
      version = "1";
      sources = {
        all = {
          url = "sources-14_r01.zip";
          sha1 = "eaf4ed7dcac46e68516a1b4aa5b0d9e5a39a7555";
        };
      };
      displayName = "Sources for Android 14";
    };
    sources.android-15 = mkGeneric {
      id = "sources;android-15";
      pname = "sources-android-15";
      version = "2";
      sources = {
        all = {
          url = "sources-15_r02.zip";
          sha1 = "e5992a5747c9590783fbbdd700337bf0c9f6b1fa";
        };
      };
      displayName = "Sources for Android 15";
    };
    sources.android-16 = mkGeneric {
      id = "sources;android-16";
      pname = "sources-android-16";
      version = "2";
      sources = {
        all = {
          url = "sources-16_r02.zip";
          sha1 = "0f83c14ed333c45d962279ab5d6bc98a0269ef84";
        };
      };
      displayName = "Sources for Android 16";
    };
    sources.android-17 = mkGeneric {
      id = "sources;android-17";
      pname = "sources-android-17";
      version = "1";
      sources = {
        all = {
          url = "sources-17_r01.zip";
          sha1 = "6f1f18cd2d2b1852d7f6892df9cee3823349d43a";
        };
      };
      displayName = "Sources for Android 17";
    };
    sources.android-18 = mkGeneric {
      id = "sources;android-18";
      pname = "sources-android-18";
      version = "1";
      sources = {
        all = {
          url = "sources-18_r01.zip";
          sha1 = "8b49fdf7433f4881a2bfb559b5dd05d8ec65fb78";
        };
      };
      displayName = "Sources for Android 18";
    };
    sources.android-19 = mkGeneric {
      id = "sources;android-19";
      pname = "sources-android-19";
      version = "2";
      sources = {
        all = {
          url = "sources-19_r02.zip";
          sha1 = "433a1d043ef77561571250e94cb7a0ef24a202e7";
        };
      };
      displayName = "Sources for Android 19";
    };
    sources.android-20 = mkGeneric {
      id = "sources;android-20";
      pname = "sources-android-20";
      version = "1";
      sources = {
        all = {
          url = "sources-20_r01.zip";
          sha1 = "8da3e40f2625f9f7ef38b7e403f49f67226c0d76";
        };
      };
      displayName = "Sources for Android 20";
    };
    sources.android-21 = mkGeneric {
      id = "sources;android-21";
      pname = "sources-android-21";
      version = "1";
      sources = {
        all = {
          url = "sources-21_r01.zip";
          sha1 = "137a5044915d32bea297a8c1552684802bbc2e25";
        };
      };
      displayName = "Sources for Android 21";
    };
    sources.android-22 = mkGeneric {
      id = "sources;android-22";
      pname = "sources-android-22";
      version = "1";
      sources = {
        all = {
          url = "sources-22_r01.zip";
          sha1 = "98320e13976d11597a4a730a8d203ac9a03ed5a6";
        };
      };
      displayName = "Sources for Android 22";
    };
    sources.android-23 = mkGeneric {
      id = "sources;android-23";
      pname = "sources-android-23";
      version = "1";
      sources = {
        all = {
          url = "sources-23_r01.zip";
          sha1 = "b0f15da2762b42f543c5e364c2b15b198cc99cc2";
        };
      };
      displayName = "Sources for Android 23";
    };
    sources.android-24 = mkGeneric {
      id = "sources;android-24";
      pname = "sources-android-24";
      version = "1";
      sources = {
        all = {
          url = "sources-24_r01.zip";
          sha1 = "6b96115830a83d654479f32ce4b724ca9011148b";
        };
      };
      displayName = "Sources for Android 24";
    };
    sources.android-25 = mkGeneric {
      id = "sources;android-25";
      pname = "sources-android-25";
      version = "1";
      sources = {
        all = {
          url = "sources-25_r01.zip";
          sha1 = "bbc72efd1a9bad87cc507e308f0d29aad438c52c";
        };
      };
      displayName = "Sources for Android 25";
    };
    sources.android-26 = mkGeneric {
      id = "sources;android-26";
      pname = "sources-android-26";
      version = "1";
      sources = {
        all = {
          url = "sources-26_r01.zip";
          sha1 = "2af701ee3223d580409288540b1d06932fd8f9b9";
        };
      };
      displayName = "Sources for Android 26";
    };
    sources.android-27 = mkGeneric {
      id = "sources;android-27";
      pname = "sources-android-27";
      version = "1";
      sources = {
        all = {
          url = "sources-27_r01.zip";
          sha1 = "7b714670561d08f54751af42aca929867b806596";
        };
      };
      displayName = "Sources for Android 27";
    };
    sources.android-28 = mkGeneric {
      id = "sources;android-28";
      pname = "sources-android-28";
      version = "1";
      sources = {
        all = {
          url = "sources-28_r01.zip";
          sha1 = "5610e0c24235ee3fa343c899ddd551be30315255";
        };
      };
      displayName = "Sources for Android 28";
    };
    sources.android-29 = mkGeneric {
      id = "sources;android-29";
      pname = "sources-android-29";
      version = "1";
      sources = {
        all = {
          url = "sources-29_r01.zip";
          sha1 = "d0ad249e152b3a8fe3cb7c4a329453a048be29e4";
        };
      };
      displayName = "Sources for Android 29";
    };
    tools = mkTools {
      id = "tools";
      pname = "tools";
      version = "26.1.1";
      sources = {
        darwin = {
          url = "sdk-tools-darwin-4333796.zip";
          sha1 = "ed85ea7b59bc3483ce0af4c198523ba044e083ad";
        };
        linux = {
          url = "sdk-tools-linux-4333796.zip";
          sha1 = "8c7c28554a32318461802c1291d76fccfafde054";
        };
        windows = {
          url = "sdk-tools-windows-4333796.zip";
          sha1 = "aa298b5346ee0d63940d13609fe6bec621384510";
        };
      };
      displayName = "Android SDK Tools";
    };
  };
  licenses = {
    android-sdk-license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
      text = ''todo'';
    };
  };
}