# Generated by nix-android-repo

{ mkBuildTools
, mkCmdlineTools
, mkEmulator
, mkNdk
, mkNdkBundle
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSrcOnly
}: {
  add-ons-addon-google-gdk-google-19 = mkSrcOnly {
    id = "add-ons;addon-google_gdk-google-19";
    pname = "add-ons-addon-google-gdk-google-19";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/glass/google-gdk.zip";
        sha1 = "52cadbec4d42ce68a667e7e4ea461ef8b81924ef";
      };
    };
    displayName = "Glass Development Kit Preview";
    path = "add-ons/addon-google_gdk-google-19";
    license = {
      id = "google-gdk-license";
      hash = "33b6a2b64607f11b759f320ef9dff4ae5c47d97a";
    };
    xml = ./add-ons-addon-google-gdk-google-19.xml;
  };
  extras-intel-Hardware-Accelerated-Execution-Manager = mkSrcOnly {
    id = "extras;intel;Hardware_Accelerated_Execution_Manager";
    pname = "extras-intel-Hardware-Accelerated-Execution-Manager";
    version = "7.6.5";
    sources = {
      windows = {
        url = "https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip";
        sha1 = "38a44a67907330bb39d8228082cc876da54f7dfc";
      };
    };
    displayName = "Intel x86 Emulator Accelerator (HAXM installer) - Deprecated";
    path = "extras/intel/Hardware_Accelerated_Execution_Manager";
    license = {
      id = "intel-android-extra-license";
      hash = "d975f751698a77b662f1254ddbeed3901e976f5a";
    };
    xml = ./extras-intel-Hardware-Accelerated-Execution-Manager.xml;
  };
  system-images-android-30-android-wear-cn-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;arm64-v8a";
    pname = "system-images-android-30-android-wear-cn-arm64-v8a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/arm64-v8a-30_r12.zip";
        sha1 = "ef7b5554a5f77fb33c7965604552411c155a38ac";
      };
    };
    displayName = "China version of Wear OS 3 ARM 64 v8a System Image";
    path = "system-images/android-30/android-wear-cn/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-arm64-v8a.xml;
  };
  system-images-android-30-android-wear-cn-x86 = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;x86";
    pname = "system-images-android-30-android-wear-cn-x86";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/x86-30_r12.zip";
        sha1 = "42548b2bd1696ad6bd2f01a1cf83ef7a10971932";
      };
    };
    displayName = "China version of Wear OS 3 Intel x86 Atom System Image";
    path = "system-images/android-30/android-wear-cn/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-x86.xml;
  };
}