# Generated by nix-android-repo

{ mkBuildTools
, mkCmdlineTools
, mkEmulator
, mkNdk
, mkNdkBundle
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSrcOnly
}: {
  add-ons-addon-google-gdk-google-19 = mkSrcOnly {
    id = "add-ons;addon-google_gdk-google-19";
    pname = "add-ons-addon-google-gdk-google-19";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/glass/google-gdk.zip";
        sha1 = "52cadbec4d42ce68a667e7e4ea461ef8b81924ef";
      };
    };
    displayName = "Glass Development Kit Preview";
    path = "add-ons/addon-google_gdk-google-19";
    license = {
      id = "google-gdk-license";
      hash = "33b6a2b64607f11b759f320ef9dff4ae5c47d97a";
    };
    xml = ./add-ons-addon-google-gdk-google-19.xml;
  };
  extras-intel-Hardware-Accelerated-Execution-Manager = mkSrcOnly {
    id = "extras;intel;Hardware_Accelerated_Execution_Manager";
    pname = "extras-intel-Hardware-Accelerated-Execution-Manager";
    version = "7.6.5";
    sources = {
      windows = {
        url = "https://dl.google.com/android/repository/extras/intel/haxm-windows_v7_6_5.zip";
        sha1 = "38a44a67907330bb39d8228082cc876da54f7dfc";
      };
    };
    displayName = "Intel x86 Emulator Accelerator (HAXM installer) - Deprecated";
    path = "extras/intel/Hardware_Accelerated_Execution_Manager";
    license = {
      id = "intel-android-extra-license";
      hash = "d975f751698a77b662f1254ddbeed3901e976f5a";
    };
    xml = ./extras-intel-Hardware-Accelerated-Execution-Manager.xml;
  };
  system-images-android-10-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-10;default;armeabi-v7a";
    pname = "system-images-android-10-default-armeabi-v7a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-10_r05.zip";
        sha1 = "8537616a7add47cce24c60f18bc2429e3dc90ae3";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-10/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-10-default-armeabi-v7a.xml;
  };
  system-images-android-10-default-x86 = mkSrcOnly {
    id = "system-images;android-10;default;x86";
    pname = "system-images-android-10-default-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-10_r05.zip";
        sha1 = "a166d5ccbb165e1dd5464fbfeec30a61f77790d8";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-10/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-10-default-x86.xml;
  };
  system-images-android-14-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-14;default;armeabi-v7a";
    pname = "system-images-android-14-default-armeabi-v7a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/sysimg_armv7a-14_r02.zip";
        sha1 = "d8991b0c06b18d7d6ed4169d67460ee1add6661b";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-14/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-14-default-armeabi-v7a.xml;
  };
  system-images-android-15-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-15;default;armeabi-v7a";
    pname = "system-images-android-15-default-armeabi-v7a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-15_r05.zip";
        sha1 = "03d7ed95a9d3b107e3f2e5b166d017ea12529e70";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-15/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-15-default-armeabi-v7a.xml;
  };
  system-images-android-15-default-x86 = mkSrcOnly {
    id = "system-images;android-15;default;x86";
    pname = "system-images-android-15-default-x86";
    version = "7";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-15_r07.zip";
        sha1 = "61381aef3fd0cdc8255cb3298072a920c80186ca";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-15/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-15-default-x86.xml;
  };
  system-images-android-16-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-16;default;armeabi-v7a";
    pname = "system-images-android-16-default-armeabi-v7a";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-16_r06.zip";
        sha1 = "69b944b0d5a18c8563fa80d7d229af64890f724e";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-16/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-16-default-armeabi-v7a.xml;
  };
  system-images-android-16-default-mips = mkSrcOnly {
    id = "system-images;android-16;default;mips";
    pname = "system-images-android-16-default-mips";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/sysimg_mips-16_r04.zip";
        sha1 = "67943c54fb3943943ffeb05fdd39c0b753681f6e";
      };
    };
    displayName = "MIPS System Image";
    path = "system-images/android-16/default/mips";
    license = {
      id = "mips-android-sysimage-license";
      hash = "e9acab5b5fbb560a72cfaecce8946896ff6aab9d";
    };
    xml = ./system-images-android-16-default-mips.xml;
  };
  system-images-android-16-default-x86 = mkSrcOnly {
    id = "system-images;android-16;default;x86";
    pname = "system-images-android-16-default-x86";
    version = "7";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-16_r07.zip";
        sha1 = "ee6718e7556c8f8bd8d3f470b34f2c5dbf9bcff4";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-16/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-16-default-x86.xml;
  };
  system-images-android-17-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-17;default;armeabi-v7a";
    pname = "system-images-android-17-default-armeabi-v7a";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-17_r06.zip";
        sha1 = "a18a3fd0958ec4ef52507f58e414fc5c7dfd59d6";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-17/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-17-default-armeabi-v7a.xml;
  };
  system-images-android-17-default-mips = mkSrcOnly {
    id = "system-images;android-17;default;mips";
    pname = "system-images-android-17-default-mips";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/sysimg_mips-17_r01.zip";
        sha1 = "f0c6e153bd584c29e51b5c9723cfbf30f996a05d";
      };
    };
    displayName = "MIPS System Image";
    path = "system-images/android-17/default/mips";
    license = {
      id = "mips-android-sysimage-license";
      hash = "e9acab5b5fbb560a72cfaecce8946896ff6aab9d";
    };
    xml = ./system-images-android-17-default-mips.xml;
  };
  system-images-android-17-default-x86 = mkSrcOnly {
    id = "system-images;android-17;default;x86";
    pname = "system-images-android-17-default-x86";
    version = "7";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-17_r07.zip";
        sha1 = "1ad5ffb51e31f5fe9fa47411fed2c2ade9a33865";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-17/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-17-default-x86.xml;
  };
  system-images-android-18-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-18;default;armeabi-v7a";
    pname = "system-images-android-18-default-armeabi-v7a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-18_r05.zip";
        sha1 = "580b583720f7de671040d5917c8c9db0c7aa03fd";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-18/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-18-default-armeabi-v7a.xml;
  };
  system-images-android-18-default-x86 = mkSrcOnly {
    id = "system-images;android-18;default;x86";
    pname = "system-images-android-18-default-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-18_r04.zip";
        sha1 = "7a4ced4d9b0ab48047825491b4072dc2eb9b610e";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-18/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-18-default-x86.xml;
  };
  system-images-android-19-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-19;default;armeabi-v7a";
    pname = "system-images-android-19-default-armeabi-v7a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-19_r05.zip";
        sha1 = "d1a5fd4f2e1c013c3d3d9bfe7e9db908c3ed56fa";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-19/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-19-default-armeabi-v7a.xml;
  };
  system-images-android-19-default-x86 = mkSrcOnly {
    id = "system-images;android-19;default;x86";
    pname = "system-images-android-19-default-x86";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-19_r06.zip";
        sha1 = "2ac82153aae97f7eae4c5a0761224fe04321d03d";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-19/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-19-default-x86.xml;
  };
  system-images-android-21-android-tv-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-21;android-tv;armeabi-v7a";
    pname = "system-images-android-21-android-tv-armeabi-v7a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/armeabi-v7a-21_r03.zip";
        sha1 = "b63e28a47f11b639dd94981a458b7abfa89ac331";
      };
    };
    displayName = "Android TV ARM EABI v7a System Image";
    path = "system-images/android-21/android-tv/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-android-tv-armeabi-v7a.xml;
  };
  system-images-android-21-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-21;android-tv;x86";
    pname = "system-images-android-21-android-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-21_r03.zip";
        sha1 = "2f8a1988188d6abfd6c6395baeb4471a034dc1e8";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-21/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-android-tv-x86.xml;
  };
  system-images-android-21-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-21;default;arm64-v8a";
    pname = "system-images-android-21-default-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-21_r04.zip";
        sha1 = "c4375f1b4b4cd21a8617660e25f621cedcbd8332";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-21/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-default-arm64-v8a.xml;
  };
  system-images-android-21-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-21;default;armeabi-v7a";
    pname = "system-images-android-21-default-armeabi-v7a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-21_r04.zip";
        sha1 = "8c606f81306564b65e41303d2603e4c42ded0d10";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-21/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-default-armeabi-v7a.xml;
  };
  system-images-android-21-default-x86 = mkSrcOnly {
    id = "system-images;android-21;default;x86";
    pname = "system-images-android-21-default-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-21_r05.zip";
        sha1 = "00f0eb0a1003efe3316347f762e20a85d8749cff";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-21/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-default-x86.xml;
  };
  system-images-android-21-default-x86-64 = mkSrcOnly {
    id = "system-images;android-21;default;x86_64";
    pname = "system-images-android-21-default-x86-64";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-21_r05.zip";
        sha1 = "9078a095825a69e5e215713f0866c83cef65a342";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-21/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-21-default-x86-64.xml;
  };
  system-images-android-22-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-22;android-tv;x86";
    pname = "system-images-android-22-android-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-22_r03.zip";
        sha1 = "c78efd5a155622eb490be9d326f5783993375c35";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-22/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-22-android-tv-x86.xml;
  };
  system-images-android-22-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-22;default;arm64-v8a";
    pname = "system-images-android-22-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-22_r02.zip";
        sha1 = "703e27a9a4fb7a6e763cb7d713b89e5249a8fc99";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-22/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-22-default-arm64-v8a.xml;
  };
  system-images-android-22-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-22;default;armeabi-v7a";
    pname = "system-images-android-22-default-armeabi-v7a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-22_r02.zip";
        sha1 = "2114ec015dbf3a16cbcb4f63e8a84a1b206a07a1";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-22/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-22-default-armeabi-v7a.xml;
  };
  system-images-android-22-default-x86 = mkSrcOnly {
    id = "system-images;android-22;default;x86";
    pname = "system-images-android-22-default-x86";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-22_r06.zip";
        sha1 = "e33e2a6cc3f1cc56b2019dbef3917d2eeb26f54e";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-22/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-22-default-x86.xml;
  };
  system-images-android-22-default-x86-64 = mkSrcOnly {
    id = "system-images;android-22;default;x86_64";
    pname = "system-images-android-22-default-x86-64";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-22_r06.zip";
        sha1 = "5db3b27f78cd9c4c5092b1cad5a5dd479fb5b2e4";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-22/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-22-default-x86-64.xml;
  };
  system-images-android-23-android-tv-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-23;android-tv;armeabi-v7a";
    pname = "system-images-android-23-android-tv-armeabi-v7a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/armeabi-v7a-23_r12.zip";
        sha1 = "bd84678ae8caf71d584f5210e866b2807e7b4b52";
      };
    };
    displayName = "Android TV ARM EABI v7a System Image";
    path = "system-images/android-23/android-tv/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-android-tv-armeabi-v7a.xml;
  };
  system-images-android-23-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-23;android-tv;x86";
    pname = "system-images-android-23-android-tv-x86";
    version = "21";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-23_r21.zip";
        sha1 = "094575ec634a662115a7a4c2b63d1743dfbca43c";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-23/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-android-tv-x86.xml;
  };
  system-images-android-23-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-23;default;arm64-v8a";
    pname = "system-images-android-23-default-arm64-v8a";
    version = "7";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-23_r07.zip";
        sha1 = "ac18f3bd717e02804eee585e029f5dbc1a2616bf";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-23/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-default-arm64-v8a.xml;
  };
  system-images-android-23-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-23;default;armeabi-v7a";
    pname = "system-images-android-23-default-armeabi-v7a";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-23_r06.zip";
        sha1 = "7cf2ad756e54a3acfd81064b63cb0cb9dff2798d";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-23/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-default-armeabi-v7a.xml;
  };
  system-images-android-23-default-x86 = mkSrcOnly {
    id = "system-images;android-23;default;x86";
    pname = "system-images-android-23-default-x86";
    version = "10";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-23_r10.zip";
        sha1 = "f6c3e3dd7bd951454795aa75c3a145fd05ac25bb";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-23/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-default-x86.xml;
  };
  system-images-android-23-default-x86-64 = mkSrcOnly {
    id = "system-images;android-23;default;x86_64";
    pname = "system-images-android-23-default-x86-64";
    version = "10";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-23_r10.zip";
        sha1 = "7cbc291483ca07dc67b71268c5f08a5755f50f51";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-23/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-23-default-x86-64.xml;
  };
  system-images-android-24-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-24;android-tv;x86";
    pname = "system-images-android-24-android-tv-x86";
    version = "22";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-24_r22.zip";
        sha1 = "ef7890e565f4e3544fd23613b437d4418fb10f99";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-24/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-24-android-tv-x86.xml;
  };
  system-images-android-24-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-24;default;arm64-v8a";
    pname = "system-images-android-24-default-arm64-v8a";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-24_r09.zip";
        sha1 = "e88ebdf4533efa0370603ee4ab0e7834e0cc364f";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-24/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-24-default-arm64-v8a.xml;
  };
  system-images-android-24-default-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-24;default;armeabi-v7a";
    pname = "system-images-android-24-default-armeabi-v7a";
    version = "7";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/armeabi-v7a-24_r07.zip";
        sha1 = "3454546b4eed2d6c3dd06d47757d6da9f4176033";
      };
    };
    displayName = "ARM EABI v7a System Image";
    path = "system-images/android-24/default/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-24-default-armeabi-v7a.xml;
  };
  system-images-android-24-default-x86 = mkSrcOnly {
    id = "system-images;android-24;default;x86";
    pname = "system-images-android-24-default-x86";
    version = "8";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-24_r08.zip";
        sha1 = "c1cae7634b0216c0b5990f2c144eb8ca948e3511";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-24/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-24-default-x86.xml;
  };
  system-images-android-24-default-x86-64 = mkSrcOnly {
    id = "system-images;android-24;default;x86_64";
    pname = "system-images-android-24-default-x86-64";
    version = "8";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-24_r08.zip";
        sha1 = "f6559e1949a5879f31a9662f4f0e50ad60181684";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-24/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-24-default-x86-64.xml;
  };
  system-images-android-25-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-25;android-tv;x86";
    pname = "system-images-android-25-android-tv-x86";
    version = "16";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-25_r16.zip";
        sha1 = "faae592bc991001b1880a8198d729b25855cc34b";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-25/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-android-tv-x86.xml;
  };
  system-images-android-25-android-wear-armeabi-v7a = mkSrcOnly {
    id = "system-images;android-25;android-wear;armeabi-v7a";
    pname = "system-images-android-25-android-wear-armeabi-v7a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/armeabi-v7a-25_r03.zip";
        sha1 = "76d3568a4e08023047af7d13025a35c9bf1d7e5c";
      };
    };
    displayName = "Android Wear ARM EABI v7a System Image";
    path = "system-images/android-25/android-wear/armeabi-v7a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-android-wear-armeabi-v7a.xml;
  };
  system-images-android-25-android-wear-x86 = mkSrcOnly {
    id = "system-images;android-25;android-wear;x86";
    pname = "system-images-android-25-android-wear-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/x86-25_r03.zip";
        sha1 = "693fce7b487a65491a4e88e9f740959688c9dbe6";
      };
    };
    displayName = "Android Wear Intel x86 Atom System Image";
    path = "system-images/android-25/android-wear/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-android-wear-x86.xml;
  };
  system-images-android-25-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-25;default;arm64-v8a";
    pname = "system-images-android-25-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-25_r02.zip";
        sha1 = "b39d359623323a1b4906c071dec396040016ea73";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-25/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-default-arm64-v8a.xml;
  };
  system-images-android-25-default-x86 = mkSrcOnly {
    id = "system-images;android-25;default;x86";
    pname = "system-images-android-25-default-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-25_r01.zip";
        sha1 = "78ce7eb1387d598685633b9f7cbb300c3d3aeb5f";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-25/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-default-x86.xml;
  };
  system-images-android-25-default-x86-64 = mkSrcOnly {
    id = "system-images;android-25;default;x86_64";
    pname = "system-images-android-25-default-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-25_r01.zip";
        sha1 = "7093d7b39216020226ff430a3b7b81c94d31ad37";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-25/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-25-default-x86-64.xml;
  };
  system-images-android-26-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-26;android-tv;x86";
    pname = "system-images-android-26-android-tv-x86";
    version = "14";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-26_r14.zip";
        sha1 = "f908b3c81a03513a756c17a197faecfc91e437df";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-26/android-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-26-android-tv-x86.xml;
  };
  system-images-android-26-android-wear-x86 = mkSrcOnly {
    id = "system-images;android-26;android-wear;x86";
    pname = "system-images-android-26-android-wear-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/x86-26_r04.zip";
        sha1 = "fbffa91b936ca18fcc1e0bab2b52a8b0835cbb1c";
      };
    };
    displayName = "Android Wear Intel x86 Atom System Image";
    path = "system-images/android-26/android-wear/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-26-android-wear-x86.xml;
  };
  system-images-android-26-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-26;default;arm64-v8a";
    pname = "system-images-android-26-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-26_r02.zip";
        sha1 = "12353141d08dd302fbebc03872f0e1ca7357c55f";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-26/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-26-default-arm64-v8a.xml;
  };
  system-images-android-26-default-x86 = mkSrcOnly {
    id = "system-images;android-26;default;x86";
    pname = "system-images-android-26-default-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-26_r01.zip";
        sha1 = "e613d6e0da668e30daf547f3c6627a6352846f90";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-26/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-26-default-x86.xml;
  };
  system-images-android-26-default-x86-64 = mkSrcOnly {
    id = "system-images;android-26;default;x86_64";
    pname = "system-images-android-26-default-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-26_r01.zip";
        sha1 = "432f149c048bffce7f9de526ec65b336daf7a0a3";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-26/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-26-default-x86-64.xml;
  };
  system-images-android-27-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-27;android-tv;x86";
    pname = "system-images-android-27-android-tv-x86";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-27_r09.zip";
        sha1 = "b7d2a9349cdb1da9dafbd42de7378f6f1933d193";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-27/android-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-27-android-tv-x86.xml;
  };
  system-images-android-27-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-27;default;arm64-v8a";
    pname = "system-images-android-27-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-27_r02.zip";
        sha1 = "e014473ac510cc9d8e9b412826332923277fa827";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-27/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-27-default-arm64-v8a.xml;
  };
  system-images-android-27-default-x86 = mkSrcOnly {
    id = "system-images;android-27;default;x86";
    pname = "system-images-android-27-default-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-27_r01.zip";
        sha1 = "4ec990fac7b62958decd12e18a4cd389dfe7c582";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-27/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-27-default-x86.xml;
  };
  system-images-android-27-default-x86-64 = mkSrcOnly {
    id = "system-images;android-27;default;x86_64";
    pname = "system-images-android-27-default-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-27_r01.zip";
        sha1 = "2878261011a59ca3de29dc5b457a495fdb268d60";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-27/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-27-default-x86-64.xml;
  };
  system-images-android-28-android-automotive-playstore-x86 = mkSrcOnly {
    id = "system-images;android-28;android-automotive-playstore;x86";
    pname = "system-images-android-28-android-automotive-playstore-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/x86-28_r05.zip";
        sha1 = "a1f224245056ddaa89651e379efbde7357b15046";
      };
    };
    displayName = "Automotive Intel x86 Atom System Image";
    path = "system-images/android-28/android-automotive-playstore/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-28-android-automotive-playstore-x86.xml;
  };
  system-images-android-28-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-28;android-tv;x86";
    pname = "system-images-android-28-android-tv-x86";
    version = "10";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-28_r10.zip";
        sha1 = "4c13edca32c1abb899a0702fe6972087712bcb78";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-28/android-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-28-android-tv-x86.xml;
  };
  system-images-android-28-android-wear-x86 = mkSrcOnly {
    id = "system-images;android-28;android-wear;x86";
    pname = "system-images-android-28-android-wear-x86";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/x86-28_r09.zip";
        sha1 = "3dd75066e95327baf8991915a043e53e06a2cfb5";
      };
    };
    displayName = "Wear OS Intel x86 Atom System Image";
    path = "system-images/android-28/android-wear/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-28-android-wear-x86.xml;
  };
  system-images-android-28-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-28;default;arm64-v8a";
    pname = "system-images-android-28-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-28_r02.zip";
        sha1 = "e209114dd0dfc2f4e0d328f5fd7367fec39ee1bd";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-28/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-28-default-arm64-v8a.xml;
  };
  system-images-android-28-default-x86 = mkSrcOnly {
    id = "system-images;android-28;default;x86";
    pname = "system-images-android-28-default-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-28_r04.zip";
        sha1 = "ce03c42d80c0fc6dc47f6455dbee7aa275d02780";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-28/default/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-28-default-x86.xml;
  };
  system-images-android-28-default-x86-64 = mkSrcOnly {
    id = "system-images;android-28;default;x86_64";
    pname = "system-images-android-28-default-x86-64";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-28_r04.zip";
        sha1 = "d47a85c8f4e9fd57df97814ad8884eeb0f3a0ef0";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-28/default/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-28-default-x86-64.xml;
  };
  system-images-android-29-android-automotive-playstore-x86 = mkSrcOnly {
    id = "system-images;android-29;android-automotive-playstore;x86";
    pname = "system-images-android-29-android-automotive-playstore-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/x86-29_r01.zip";
        sha1 = "8fb2624c63c34a01c27dd8085277b2a5fb8d7fbc";
      };
    };
    displayName = "Automotive with Play Store Intel x86 Atom System Image";
    path = "system-images/android-29/android-automotive-playstore/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-29-android-automotive-playstore-x86.xml;
  };
  system-images-android-29-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-29;android-tv;x86";
    pname = "system-images-android-29-android-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-29_r03.zip";
        sha1 = "736c2f6c79493b5ee4ca0d2531a25c9eb7f9c7ab";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-29/android-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-29-android-tv-x86.xml;
  };
  system-images-android-29-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-29;default;arm64-v8a";
    pname = "system-images-android-29-default-arm64-v8a";
    version = "8";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-29_r08.zip";
        sha1 = "fa0d67d7430fcc84b2fe2508ea81e92ac644e264";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-29/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-29-default-arm64-v8a.xml;
  };
  system-images-android-29-default-x86 = mkSrcOnly {
    id = "system-images;android-29;default;x86";
    pname = "system-images-android-29-default-x86";
    version = "8";
    sources = {
      windows = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-29_r08-windows.zip";
        sha1 = "cc4fa13e49cb2e93770d4f2e90ea1dd2a81e315b";
      };
      darwin = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-29_r08-darwin.zip";
        sha1 = "cc4fa13e49cb2e93770d4f2e90ea1dd2a81e315b";
      };
      linux = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86-29_r08-linux.zip";
        sha1 = "cc4fa13e49cb2e93770d4f2e90ea1dd2a81e315b";
      };
    };
    displayName = "Intel x86 Atom System Image";
    path = "system-images/android-29/default/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-29-default-x86.xml;
  };
  system-images-android-29-default-x86-64 = mkSrcOnly {
    id = "system-images;android-29;default;x86_64";
    pname = "system-images-android-29-default-x86-64";
    version = "8";
    sources = {
      windows = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-29_r08-windows.zip";
        sha1 = "e4b798d6fcddff90d528d74ef22ce3dd4a2ca798";
      };
      darwin = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-29_r08-darwin.zip";
        sha1 = "e4b798d6fcddff90d528d74ef22ce3dd4a2ca798";
      };
      linux = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-29_r08-linux.zip";
        sha1 = "e4b798d6fcddff90d528d74ef22ce3dd4a2ca798";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-29/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-29-default-x86-64.xml;
  };
  system-images-android-30-android-automotive-playstore-x86-64 = mkSrcOnly {
    id = "system-images;android-30;android-automotive-playstore;x86_64";
    pname = "system-images-android-30-android-automotive-playstore-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/x86_64-30_r02.zip";
        sha1 = "7aec48997addb860118a98741458922bdec606c9";
      };
    };
    displayName = "Automotive with Play Store Intel x86_64 Atom System Image";
    path = "system-images/android-30/android-automotive-playstore/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-automotive-playstore-x86-64.xml;
  };
  system-images-android-30-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-30;android-tv;x86";
    pname = "system-images-android-30-android-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-30_r04.zip";
        sha1 = "f4151d2390fc015ddb2a7715bea9bc69a5ee0b4e";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-30/android-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-30-android-tv-x86.xml;
  };
  system-images-android-30-android-wear-cn-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;arm64-v8a";
    pname = "system-images-android-30-android-wear-cn-arm64-v8a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/arm64-v8a-30_r12.zip";
        sha1 = "ef7b5554a5f77fb33c7965604552411c155a38ac";
      };
    };
    displayName = "China version of Wear OS 3 ARM 64 v8a System Image";
    path = "system-images/android-30/android-wear-cn/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-arm64-v8a.xml;
  };
  system-images-android-30-android-wear-cn-x86 = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;x86";
    pname = "system-images-android-30-android-wear-cn-x86";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/x86-30_r12.zip";
        sha1 = "42548b2bd1696ad6bd2f01a1cf83ef7a10971932";
      };
    };
    displayName = "China version of Wear OS 3 Intel x86 Atom System Image";
    path = "system-images/android-30/android-wear-cn/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-x86.xml;
  };
  system-images-android-30-android-wear-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;android-wear;arm64-v8a";
    pname = "system-images-android-30-android-wear-arm64-v8a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/arm64-v8a-30_r12.zip";
        sha1 = "56c0c2550580f2ba1b33009c77db017dbcb3d470";
      };
    };
    displayName = "Wear OS 3 ARM 64 v8a System Image";
    path = "system-images/android-30/android-wear/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-arm64-v8a.xml;
  };
  system-images-android-30-android-wear-x86 = mkSrcOnly {
    id = "system-images;android-30;android-wear;x86";
    pname = "system-images-android-30-android-wear-x86";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/x86-30_r12.zip";
        sha1 = "73a96614a2ddcf586e4c659c436d2360bc25badc";
      };
    };
    displayName = "Wear OS 3 Intel x86 Atom System Image";
    path = "system-images/android-30/android-wear/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-x86.xml;
  };
  system-images-android-30-aosp-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;aosp_atd;arm64-v8a";
    pname = "system-images-android-30-aosp-atd-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/arm64-v8a-30_r02.zip";
        sha1 = "7aedf542eebcdb865ed2a03682abeb9518171556";
      };
    };
    displayName = "AOSP ATD ARM 64 v8a System Image";
    path = "system-images/android-30/aosp_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-30-aosp-atd-arm64-v8a.xml;
  };
  system-images-android-30-aosp-atd-x86 = mkSrcOnly {
    id = "system-images;android-30;aosp_atd;x86";
    pname = "system-images-android-30-aosp-atd-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86-30_r01.zip";
        sha1 = "ee28efbcf5b1fce3de69f0f6ef232ca1356b1131";
      };
    };
    displayName = "AOSP ATD Intel x86 Atom System Image";
    path = "system-images/android-30/aosp_atd/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-30-aosp-atd-x86.xml;
  };
  system-images-android-30-aosp-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-30;aosp_atd;x86_64";
    pname = "system-images-android-30-aosp-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86_64-30_r02.zip";
        sha1 = "5e115eb1dd616b7b9bb933ffdb3fa0a00630971b";
      };
    };
    displayName = "AOSP ATD Intel x86_64 Atom System Image";
    path = "system-images/android-30/aosp_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-aosp-atd-x86-64.xml;
  };
  system-images-android-30-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;default;arm64-v8a";
    pname = "system-images-android-30-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-30_r02.zip";
        sha1 = "e96298145a5e0bfd6da4816f51b06c520d8dba72";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-30/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-default-arm64-v8a.xml;
  };
  system-images-android-30-default-x86-64 = mkSrcOnly {
    id = "system-images;android-30;default;x86_64";
    pname = "system-images-android-30-default-x86-64";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-30_r11.zip";
        sha1 = "5e4de3946d46f88856c35efcc4d797b381456347";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-30/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-default-x86-64.xml;
  };
  system-images-android-30-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-30;google-tv;x86";
    pname = "system-images-android-30-google-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-30_r04.zip";
        sha1 = "01fe86407a8d2da53c18c56e062eff9caa11127f";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-30/google-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-30-google-tv-x86.xml;
  };
  system-images-android-30-google-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;google_atd;arm64-v8a";
    pname = "system-images-android-30-google-atd-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/arm64-v8a-30_r02.zip";
        sha1 = "df560fd209d7aa01152fe83731da17d1f431982e";
      };
    };
    displayName = "Google APIs ATD ARM 64 v8a System Image";
    path = "system-images/android-30/google_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-30-google-atd-arm64-v8a.xml;
  };
  system-images-android-30-google-atd-x86 = mkSrcOnly {
    id = "system-images;android-30;google_atd;x86";
    pname = "system-images-android-30-google-atd-x86";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86-30_r01.zip";
        sha1 = "851978eaeda43c45cacb965765aa4513ed596042";
      };
    };
    displayName = "Google APIs ATD Intel x86 Atom System Image";
    path = "system-images/android-30/google_atd/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-30-google-atd-x86.xml;
  };
  system-images-android-30-google-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-30;google_atd;x86_64";
    pname = "system-images-android-30-google-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86_64-30_r02.zip";
        sha1 = "b3137c9ad0e3dfea315f53c8a81c5b480591732d";
      };
    };
    displayName = "Google APIs ATD Intel x86_64 Atom System Image";
    path = "system-images/android-30/google_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-google-atd-x86-64.xml;
  };
  system-images-android-31-android-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;android-tv;arm64-v8a";
    pname = "system-images-android-31-android-tv-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/arm64-v8a-31_r04.zip";
        sha1 = "e8cec4080464d516e3f863d943c24055155f29bf";
      };
    };
    displayName = "Android TV ARM 64 v8a System Image";
    path = "system-images/android-31/android-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-android-tv-arm64-v8a.xml;
  };
  system-images-android-31-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-31;android-tv;x86";
    pname = "system-images-android-31-android-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-31_r04.zip";
        sha1 = "8c0b848019afade7f2a8ddb5c361178f63ec86ca";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-31/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-android-tv-x86.xml;
  };
  system-images-android-31-aosp-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;aosp_atd;arm64-v8a";
    pname = "system-images-android-31-aosp-atd-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/arm64-v8a-31_r01.zip";
        sha1 = "4c8749b6af2f0250c16e6ed1e169cb17fd015b16";
      };
    };
    displayName = "AOSP ATD ARM 64 v8a System Image";
    path = "system-images/android-31/aosp_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-31-aosp-atd-arm64-v8a.xml;
  };
  system-images-android-31-aosp-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-31;aosp_atd;x86_64";
    pname = "system-images-android-31-aosp-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86_64-31_r01.zip";
        sha1 = "fbb32895e57df097fa94bafbbefb57dc0024014e";
      };
    };
    displayName = "AOSP ATD Intel x86_64 Atom System Image";
    path = "system-images/android-31/aosp_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-aosp-atd-x86-64.xml;
  };
  system-images-android-31-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;default;arm64-v8a";
    pname = "system-images-android-31-default-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-31_r03.zip";
        sha1 = "1052df2d0afc8fe57138db19d5ebd82d10c607da";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-31/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-default-arm64-v8a.xml;
  };
  system-images-android-31-default-x86-64 = mkSrcOnly {
    id = "system-images;android-31;default;x86_64";
    pname = "system-images-android-31-default-x86-64";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-31_r05.zip";
        sha1 = "58bff3cb182c79bbfe3980fe77b87b51b9f7ad71";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-31/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-default-x86-64.xml;
  };
  system-images-android-31-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;google-tv;arm64-v8a";
    pname = "system-images-android-31-google-tv-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-31_r04.zip";
        sha1 = "ca4a27b23f532ac390f5a861362c8338b6061cb7";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-31/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-google-tv-arm64-v8a.xml;
  };
  system-images-android-31-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-31;google-tv;x86";
    pname = "system-images-android-31-google-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-31_r04.zip";
        sha1 = "892128874dbf38837dfd5f938bf717d54d5a8994";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-31/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-google-tv-x86.xml;
  };
  system-images-android-31-google-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;google_atd;arm64-v8a";
    pname = "system-images-android-31-google-atd-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/arm64-v8a-31_r01.zip";
        sha1 = "4002677e4d7874bf0951795ec730dc1272a5b95b";
      };
    };
    displayName = "Google APIs ATD ARM 64 v8a System Image";
    path = "system-images/android-31/google_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-31-google-atd-arm64-v8a.xml;
  };
  system-images-android-31-google-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-31;google_atd;x86_64";
    pname = "system-images-android-31-google-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86_64-31_r01.zip";
        sha1 = "feb32019317f4b71396db03d22e0f6a833f4e6fb";
      };
    };
    displayName = "Google APIs ATD Intel x86_64 Atom System Image";
    path = "system-images/android-31/google_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-google-atd-x86-64.xml;
  };
  system-images-android-32-android-automotive-playstore-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;android-automotive-playstore;arm64-v8a";
    pname = "system-images-android-32-android-automotive-playstore-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/arm64-v8a-32_r01.zip";
        sha1 = "1b07fe1bc8a4f5a9b249ff12d5bf142cb43a2093";
      };
    };
    displayName = "Automotive with Play Store ARM 64 v8a System Image";
    path = "system-images/android-32/android-automotive-playstore/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-32-android-automotive-playstore-arm64-v8a.xml;
  };
  system-images-android-32-android-automotive-playstore-x86-64 = mkSrcOnly {
    id = "system-images;android-32;android-automotive-playstore;x86_64";
    pname = "system-images-android-32-android-automotive-playstore-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/x86_64-32_r01.zip";
        sha1 = "8f8309ae9e25b0c5eeb869bb0cb2515021073693";
      };
    };
    displayName = "Automotive with Play Store Intel x86_64 Atom System Image";
    path = "system-images/android-32/android-automotive-playstore/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-32-android-automotive-playstore-x86-64.xml;
  };
  system-images-android-32-android-desktop-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;android-desktop;arm64-v8a";
    pname = "system-images-android-32-android-desktop-arm64-v8a";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-desktop/arm64-v8a-32_r06.zip";
        sha1 = "b003887d4ad98955e3fe23e822ca925383fa68b3";
      };
    };
    displayName = "Desktop ARM 64 v8a System Image";
    path = "system-images/android-32/android-desktop/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-32-android-desktop-arm64-v8a.xml;
  };
  system-images-android-32-android-desktop-x86-64 = mkSrcOnly {
    id = "system-images;android-32;android-desktop;x86_64";
    pname = "system-images-android-32-android-desktop-x86-64";
    version = "6";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-desktop/x86_64-32_r06.zip";
        sha1 = "267d86b8b94a8ec5324b75e4b8a71e954ddedec7";
      };
    };
    displayName = "Desktop Intel x86_64 Atom System Image";
    path = "system-images/android-32/android-desktop/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-android-desktop-x86-64.xml;
  };
  system-images-android-32-aosp-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;aosp_atd;arm64-v8a";
    pname = "system-images-android-32-aosp-atd-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/arm64-v8a-32_r01.zip";
        sha1 = "1fc9d5772e39316396b6fe035e5f96a4dc6945cb";
      };
    };
    displayName = "AOSP ATD ARM 64 v8a System Image";
    path = "system-images/android-32/aosp_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-32-aosp-atd-arm64-v8a.xml;
  };
  system-images-android-32-aosp-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-32;aosp_atd;x86_64";
    pname = "system-images-android-32-aosp-atd-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86_64-32_r01.zip";
        sha1 = "133b8c32651df60635cb9f3ea39ae2f2344a6cbc";
      };
    };
    displayName = "AOSP ATD Intel x86_64 Atom System Image";
    path = "system-images/android-32/aosp_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-32-aosp-atd-x86-64.xml;
  };
  system-images-android-32-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;default;arm64-v8a";
    pname = "system-images-android-32-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-32_r02.zip";
        sha1 = "c57d92a4131590b2a3b62f2a728766aa6bbec57f";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-32/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-32-default-arm64-v8a.xml;
  };
  system-images-android-32-default-x86-64 = mkSrcOnly {
    id = "system-images;android-32;default;x86_64";
    pname = "system-images-android-32-default-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-32_r02.zip";
        sha1 = "238452e27d6854d153b6ed119fa783189598eac4";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-32/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-32-default-x86-64.xml;
  };
  system-images-android-32-google-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;google_atd;arm64-v8a";
    pname = "system-images-android-32-google-atd-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/arm64-v8a-32_r01.zip";
        sha1 = "6eda61798c381a7a02d690b58004f5aa86d8994b";
      };
    };
    displayName = "Google APIs ATD ARM 64 v8a System Image";
    path = "system-images/android-32/google_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-32-google-atd-arm64-v8a.xml;
  };
  system-images-android-32-google-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-32;google_atd;x86_64";
    pname = "system-images-android-32-google-atd-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86_64-32_r01.zip";
        sha1 = "564c125422890641a915a28f3ffa3395fc2cc934";
      };
    };
    displayName = "Google APIs ATD Intel x86_64 Atom System Image";
    path = "system-images/android-32/google_atd/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-google-atd-x86-64.xml;
  };
  system-images-android-33-android-automotive-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;android-automotive;arm64-v8a";
    pname = "system-images-android-33-android-automotive-arm64-v8a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/arm64-v8a-33_r03.zip";
        sha1 = "d73301d912ba23df9191fcba3cfbf1dde18154e4";
      };
    };
    displayName = "Android Automotive with Google APIs ARM 64 v8a System Image";
    path = "system-images/android-33/android-automotive/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-automotive-arm64-v8a.xml;
  };
  system-images-android-33-android-automotive-x86-64 = mkSrcOnly {
    id = "system-images;android-33;android-automotive;x86_64";
    pname = "system-images-android-33-android-automotive-x86-64";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive/x86_64-33_r03.zip";
        sha1 = "318b2de8fa40d2f623c3e8434b204b2ff6026835";
      };
    };
    displayName = "Android Automotive with Google APIs Intel x86_64 Atom System Image";
    path = "system-images/android-33/android-automotive/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-automotive-x86-64.xml;
  };
  system-images-android-33-android-desktop-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;android-desktop;arm64-v8a";
    pname = "system-images-android-33-android-desktop-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-desktop/arm64-v8a-33_r04.zip";
        sha1 = "110986d18d03184a3a6d0960f0d873e5238ae065";
      };
    };
    displayName = "Desktop ARM 64 v8a System Image";
    path = "system-images/android-33/android-desktop/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-desktop-arm64-v8a.xml;
  };
  system-images-android-33-android-desktop-x86-64 = mkSrcOnly {
    id = "system-images;android-33;android-desktop;x86_64";
    pname = "system-images-android-33-android-desktop-x86-64";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-desktop/x86_64-33_r04.zip";
        sha1 = "5ff1609ce69ba1a6e40db5fc2ff3c032f88dc582";
      };
    };
    displayName = "Desktop Intel x86_64 Atom System Image";
    path = "system-images/android-33/android-desktop/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-desktop-x86-64.xml;
  };
  system-images-android-33-android-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;android-tv;arm64-v8a";
    pname = "system-images-android-33-android-tv-arm64-v8a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/arm64-v8a-33_r05.zip";
        sha1 = "41b75155961eb506b492e60e8fba590ad7baa02c";
      };
    };
    displayName = "Android TV ARM 64 v8a System Image";
    path = "system-images/android-33/android-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-tv-arm64-v8a.xml;
  };
  system-images-android-33-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-33;android-tv;x86";
    pname = "system-images-android-33-android-tv-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-33_r05.zip";
        sha1 = "ec3fe6a450ed6aa5fec2703fca68648e7813094f";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-33/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-tv-x86.xml;
  };
  system-images-android-33-android-wear-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;android-wear;arm64-v8a";
    pname = "system-images-android-33-android-wear-arm64-v8a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/arm64-v8a-33_r03.zip";
        sha1 = "949a8b23b3abb217ad2f710bbffe58d4b81dd8db";
      };
    };
    displayName = "Wear OS 4 ARM 64 v8a System Image";
    path = "system-images/android-33/android-wear/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-wear-arm64-v8a.xml;
  };
  system-images-android-33-android-wear-x86-64 = mkSrcOnly {
    id = "system-images;android-33;android-wear;x86_64";
    pname = "system-images-android-33-android-wear-x86-64";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear/x86_64-33_r03.zip";
        sha1 = "94de5073c7078126614d8b7510aa4adde4327dd5";
      };
    };
    displayName = "Wear OS 4 Intel x86_64 Atom System Image";
    path = "system-images/android-33/android-wear/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-wear-x86-64.xml;
  };
  system-images-android-33-aosp-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;aosp_atd;arm64-v8a";
    pname = "system-images-android-33-aosp-atd-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/arm64-v8a-33_r02.zip";
        sha1 = "1169bf57193024fca76f1c52470b2aab3be7d566";
      };
    };
    displayName = "AOSP ATD ARM 64 v8a System Image";
    path = "system-images/android-33/aosp_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-33-aosp-atd-arm64-v8a.xml;
  };
  system-images-android-33-aosp-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-33;aosp_atd;x86_64";
    pname = "system-images-android-33-aosp-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86_64-33_r02.zip";
        sha1 = "6f0b094b55617719294a080bc08816b4e8cb270a";
      };
    };
    displayName = "AOSP ATD Intel x86_64 Atom System Image";
    path = "system-images/android-33/aosp_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-aosp-atd-x86-64.xml;
  };
  system-images-android-33-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;default;arm64-v8a";
    pname = "system-images-android-33-default-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-33_r02.zip";
        sha1 = "69883e92b77f8705af135ee86e1d87589f8f113e";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-33/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-default-arm64-v8a.xml;
  };
  system-images-android-33-default-x86-64 = mkSrcOnly {
    id = "system-images;android-33;default;x86_64";
    pname = "system-images-android-33-default-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-33_r02.zip";
        sha1 = "d4698590184a21fe1e8754284130ad3006b5fc79";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-33/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-default-x86-64.xml;
  };
  system-images-android-33-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;google-tv;arm64-v8a";
    pname = "system-images-android-33-google-tv-arm64-v8a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-33_r05.zip";
        sha1 = "4de71a5b7566f1e2cfd07310cbe9df539ee9a0d2";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-33/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-google-tv-arm64-v8a.xml;
  };
  system-images-android-33-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-33;google-tv;x86";
    pname = "system-images-android-33-google-tv-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-33_r05.zip";
        sha1 = "f3daa88193001319f5bf2e20256675b9d6031d96";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-33/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-google-tv-x86.xml;
  };
  system-images-android-33-google-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;google_atd;arm64-v8a";
    pname = "system-images-android-33-google-atd-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/arm64-v8a-33_r02.zip";
        sha1 = "4294818d9bf5fe76556cfd92476a6d0c5a65db48";
      };
    };
    displayName = "Google APIs ATD ARM 64 v8a System Image";
    path = "system-images/android-33/google_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-33-google-atd-arm64-v8a.xml;
  };
  system-images-android-33-google-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-33;google_atd;x86_64";
    pname = "system-images-android-33-google-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86_64-33_r02.zip";
        sha1 = "311955a39ba5bf55bf5bcfa275f102e9318d0ee2";
      };
    };
    displayName = "Google APIs ATD Intel x86_64 Atom System Image";
    path = "system-images/android-33/google_atd/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-33-google-atd-x86-64.xml;
  };
  system-images-android-34-android-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;android-tv;arm64-v8a";
    pname = "system-images-android-34-android-tv-arm64-v8a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/arm64-v8a-34_r03.zip";
        sha1 = "a31d0d8326f2c82787f95dd387614274082a96a0";
      };
    };
    displayName = "Android TV ARM 64 v8a System Image";
    path = "system-images/android-34/android-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-android-tv-arm64-v8a.xml;
  };
  system-images-android-34-android-tv-x86 = mkSrcOnly {
    id = "system-images;android-34;android-tv;x86";
    pname = "system-images-android-34-android-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-tv/x86-34_r03.zip";
        sha1 = "8de1dcb502b0b4080e6f363828db64e609b3aa2a";
      };
    };
    displayName = "Android TV Intel x86 Atom System Image";
    path = "system-images/android-34/android-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-android-tv-x86.xml;
  };
  system-images-android-34-aosp-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;aosp_atd;arm64-v8a";
    pname = "system-images-android-34-aosp-atd-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/arm64-v8a-34_r02.zip";
        sha1 = "fd47af85c9e592ec140e1acf43a88c47e37560cd";
      };
    };
    displayName = "AOSP ATD ARM 64 v8a System Image";
    path = "system-images/android-34/aosp_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-34-aosp-atd-arm64-v8a.xml;
  };
  system-images-android-34-aosp-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-34;aosp_atd;x86_64";
    pname = "system-images-android-34-aosp-atd-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_atd/x86_64-34_r02.zip";
        sha1 = "9ce4068934b26fa99ca104ffe6d10dec22abb317";
      };
    };
    displayName = "AOSP ATD Intel x86_64 Atom System Image";
    path = "system-images/android-34/aosp_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-aosp-atd-x86-64.xml;
  };
  system-images-android-34-default-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;default;arm64-v8a";
    pname = "system-images-android-34-default-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/arm64-v8a-34_r04.zip";
        sha1 = "d9f2011131919abe952814e041f16f317242c3fa";
      };
    };
    displayName = "ARM 64 v8a System Image";
    path = "system-images/android-34/default/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-default-arm64-v8a.xml;
  };
  system-images-android-34-default-x86-64 = mkSrcOnly {
    id = "system-images;android-34;default;x86_64";
    pname = "system-images-android-34-default-x86-64";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android/x86_64-34_r04.zip";
        sha1 = "5f6a249f9bc3b1b4c459b13ce2eb646c9680bed1";
      };
    };
    displayName = "Intel x86_64 Atom System Image";
    path = "system-images/android-34/default/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-default-x86-64.xml;
  };
  system-images-android-34-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;google-tv;arm64-v8a";
    pname = "system-images-android-34-google-tv-arm64-v8a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-34_r03.zip";
        sha1 = "a5ecfa06ee6e4b5d5262d47dffb84136ce1645d1";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-34/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-google-tv-arm64-v8a.xml;
  };
  system-images-android-34-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-34;google-tv;x86";
    pname = "system-images-android-34-google-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-34_r03.zip";
        sha1 = "277568ce3312a7e84f49cde8252e7bdce18faedf";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-34/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-google-tv-x86.xml;
  };
  system-images-android-34-google-atd-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;google_atd;arm64-v8a";
    pname = "system-images-android-34-google-atd-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/arm64-v8a-34_r01.zip";
        sha1 = "38eba8eccbdea18d87e526922ac195bc0403f3a3";
      };
    };
    displayName = "Google APIs ATD ARM 64 System Image";
    path = "system-images/android-34/google_atd/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-34-google-atd-arm64-v8a.xml;
  };
  system-images-android-34-google-atd-x86-64 = mkSrcOnly {
    id = "system-images;android-34;google_atd;x86_64";
    pname = "system-images-android-34-google-atd-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_atd/x86_64-34_r01.zip";
        sha1 = "523082c66dd17bddeacdce42b32d5b38a7348b9f";
      };
    };
    displayName = "Google APIs ATD Intel x86_64 Atom System Image";
    path = "system-images/android-34/google_atd/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-google-atd-x86-64.xml;
  };
}