# Generated by nix-android-repo

{ mkBuildTools
, mkCmdlineTools
, mkEmulator
, mkNdk
, mkNdkBundle
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSrcOnly
}: {
  add-ons-addon-google-gdk-google-19 = mkSrcOnly {
    id = "add-ons;addon-google_gdk-google-19";
    pname = "add-ons-addon-google-gdk-google-19";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/glass/google-gdk.zip";
        sha1 = "52cadbec4d42ce68a667e7e4ea461ef8b81924ef";
      };
    };
    displayName = "Glass Development Kit Preview";
    path = "add-ons/addon-google_gdk-google-19";
    license = {
      id = "google-gdk-license";
      hash = "33b6a2b64607f11b759f320ef9dff4ae5c47d97a";
    };
    xml = ./add-ons-addon-google-gdk-google-19.xml;
  };
  system-images-android-30-android-wear-cn-arm64-v8a = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;arm64-v8a";
    pname = "system-images-android-30-android-wear-cn-arm64-v8a";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/arm64-v8a-30_r12.zip";
        sha1 = "ef7b5554a5f77fb33c7965604552411c155a38ac";
      };
    };
    displayName = "China version of Wear OS 3 ARM 64 v8a System Image";
    path = "system-images/android-30/android-wear-cn/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-arm64-v8a.xml;
  };
  system-images-android-30-android-wear-cn-x86 = mkSrcOnly {
    id = "system-images;android-30;android-wear-cn;x86";
    pname = "system-images-android-30-android-wear-cn-x86";
    version = "12";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-wear-cn/x86-30_r12.zip";
        sha1 = "42548b2bd1696ad6bd2f01a1cf83ef7a10971932";
      };
    };
    displayName = "China version of Wear OS 3 Intel x86 Atom System Image";
    path = "system-images/android-30/android-wear-cn/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-30-android-wear-cn-x86.xml;
  };
  system-images-android-30-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-30;google-tv;x86";
    pname = "system-images-android-30-google-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-30_r04.zip";
        sha1 = "01fe86407a8d2da53c18c56e062eff9caa11127f";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-30/google-tv/x86";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-30-google-tv-x86.xml;
  };
  system-images-android-31-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-31;google-tv;arm64-v8a";
    pname = "system-images-android-31-google-tv-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-31_r04.zip";
        sha1 = "ca4a27b23f532ac390f5a861362c8338b6061cb7";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-31/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-google-tv-arm64-v8a.xml;
  };
  system-images-android-31-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-31;google-tv;x86";
    pname = "system-images-android-31-google-tv-x86";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-31_r04.zip";
        sha1 = "892128874dbf38837dfd5f938bf717d54d5a8994";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-31/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-31-google-tv-x86.xml;
  };
  system-images-android-32-android-automotive-distant-display-playstore-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;android-automotive-distant-display-playstore;arm64-v8a";
    pname = "system-images-android-32-android-automotive-distant-display-playstore-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/arm64-v8a-32_r02.zip";
        sha1 = "56299e72b5f7ff447b302d4d52428f868f633474";
      };
    };
    displayName = "Automotive Distant Display with Google Play arm64-v8a System Image";
    path = "system-images/android-32/android-automotive-distant-display-playstore/arm64-v8a";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-android-automotive-distant-display-playstore-arm64-v8a.xml;
  };
  system-images-android-32-android-automotive-distant-display-playstore-x86-64 = mkSrcOnly {
    id = "system-images;android-32;android-automotive-distant-display-playstore;x86_64";
    pname = "system-images-android-32-android-automotive-distant-display-playstore-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/x86_64-32_r02.zip";
        sha1 = "a992652c2b7d173f367907f8ca11dac697d5ba37";
      };
    };
    displayName = "Automotive Distant Display with Google Play x86_64 System Image";
    path = "system-images/android-32/android-automotive-distant-display-playstore/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-android-automotive-distant-display-playstore-x86-64.xml;
  };
  system-images-android-32-android-automotive-distant-display-arm64-v8a = mkSrcOnly {
    id = "system-images;android-32;android-automotive-distant-display;arm64-v8a";
    pname = "system-images-android-32-android-automotive-distant-display-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/arm64-v8a-32_r01.zip";
        sha1 = "8f4e0ab48441a414493273576410c62f052fba36";
      };
    };
    displayName = "Automotive Distant Display with Google APIs arm64-v8a System Image";
    path = "system-images/android-32/android-automotive-distant-display/arm64-v8a";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-android-automotive-distant-display-arm64-v8a.xml;
  };
  system-images-android-32-android-automotive-distant-display-x86-64 = mkSrcOnly {
    id = "system-images;android-32;android-automotive-distant-display;x86_64";
    pname = "system-images-android-32-android-automotive-distant-display-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/x86_64-32_r01.zip";
        sha1 = "dbecd60f4ae422a93bd53548bcbe464f33c87a3d";
      };
    };
    displayName = "Automotive Distant Display with Google APIs x86_64 System Image";
    path = "system-images/android-32/android-automotive-distant-display/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-32-android-automotive-distant-display-x86-64.xml;
  };
  system-images-android-33-android-automotive-distant-display-playstore-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;android-automotive-distant-display-playstore;arm64-v8a";
    pname = "system-images-android-33-android-automotive-distant-display-playstore-arm64-v8a";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/arm64-v8a-33_r01.zip";
        sha1 = "389437a6b29faa36b17fd6c0423f3aabaccadc95";
      };
    };
    displayName = "Automotive Distant Display with Google Play arm64-v8a System Image";
    path = "system-images/android-33/android-automotive-distant-display-playstore/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-automotive-distant-display-playstore-arm64-v8a.xml;
  };
  system-images-android-33-android-automotive-distant-display-playstore-x86-64 = mkSrcOnly {
    id = "system-images;android-33;android-automotive-distant-display-playstore;x86_64";
    pname = "system-images-android-33-android-automotive-distant-display-playstore-x86-64";
    version = "1";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/android-automotive-distantdisplay/x86_64-33_r01.zip";
        sha1 = "c0f01bbe30166edd4779b141ef59fc8b4e9a10c1";
      };
    };
    displayName = "Automotive Distant Display with Google Play x86_64 System Image";
    path = "system-images/android-33/android-automotive-distant-display-playstore/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-android-automotive-distant-display-playstore-x86-64.xml;
  };
  system-images-android-33-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-33;google-tv;arm64-v8a";
    pname = "system-images-android-33-google-tv-arm64-v8a";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-33_r05.zip";
        sha1 = "4de71a5b7566f1e2cfd07310cbe9df539ee9a0d2";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-33/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-google-tv-arm64-v8a.xml;
  };
  system-images-android-33-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-33;google-tv;x86";
    pname = "system-images-android-33-google-tv-x86";
    version = "5";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-33_r05.zip";
        sha1 = "f3daa88193001319f5bf2e20256675b9d6031d96";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-33/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-33-google-tv-x86.xml;
  };
  system-images-android-34-aosp-tablet-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;aosp_tablet;arm64-v8a";
    pname = "system-images-android-34-aosp-tablet-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_tablet/arm64-v8a-34_r02.zip";
        sha1 = "71631bd45b4186d963f91e795457cdf23f41e596";
      };
    };
    displayName = "AOSP Tablet ARM 64 v8a System Image";
    path = "system-images/android-34/aosp_tablet/arm64-v8a";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-34-aosp-tablet-arm64-v8a.xml;
  };
  system-images-android-34-aosp-tablet-x86-64 = mkSrcOnly {
    id = "system-images;android-34;aosp_tablet;x86_64";
    pname = "system-images-android-34-aosp-tablet-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/aosp_tablet/x86_64-34_r02.zip";
        sha1 = "f1df67015afebc72014b2e482f6d12258a300bf7";
      };
    };
    displayName = "AOSP Tablet Intel x86_64 Atom System Image";
    path = "system-images/android-34/aosp_tablet/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-34-aosp-tablet-x86-64.xml;
  };
  system-images-android-34-google-tv-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;google-tv;arm64-v8a";
    pname = "system-images-android-34-google-tv-arm64-v8a";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/arm64-v8a-34_r03.zip";
        sha1 = "a5ecfa06ee6e4b5d5262d47dffb84136ce1645d1";
      };
    };
    displayName = "Google TV ARM 64 v8a System Image";
    path = "system-images/android-34/google-tv/arm64-v8a";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-google-tv-arm64-v8a.xml;
  };
  system-images-android-34-google-tv-x86 = mkSrcOnly {
    id = "system-images;android-34;google-tv;x86";
    pname = "system-images-android-34-google-tv-x86";
    version = "3";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google-tv/x86-34_r03.zip";
        sha1 = "277568ce3312a7e84f49cde8252e7bdce18faedf";
      };
    };
    displayName = "Google TV Intel x86 Atom System Image";
    path = "system-images/android-34/google-tv/x86";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-34-google-tv-x86.xml;
  };
  system-images-android-34-google-xr-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;google-xr;arm64-v8a";
    pname = "system-images-android-34-google-xr-arm64-v8a";
    version = "4";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_xr/xr-arm64-v8a-playstore-34_r04.zip";
        sha1 = "3ef7800026c62ab04fff6f1a12af57902c88b8e6";
      };
    };
    displayName = "Google Play XR ARM 64 v8a System Image";
    path = "system-images/android-34/google-xr/arm64-v8a";
    license = {
      id = "android-googlexr-license";
      hash = "ceff83576aac4f7f37cb98fe189e9fb3c49d3b81";
    };
    xml = ./system-images-android-34-google-xr-arm64-v8a.xml;
  };
  system-images-android-34-google-xr-x86-64 = mkSrcOnly {
    id = "system-images;android-34;google-xr;x86_64";
    pname = "system-images-android-34-google-xr-x86-64";
    version = "4";
    sources = {
      linux = {
        url = "https://dl.google.com/android/repository/sys-img/google_xr/xr-x86_64-playstore-34_r04-linux.zip";
        sha1 = "8d21a5d2afa0d0902578fe886c2abf6139c01436";
      };
      windows = {
        url = "https://dl.google.com/android/repository/sys-img/google_xr/xr-x86_64-playstore-34_r04-windows.zip";
        sha1 = "900fb6f084ddb3951a3f1c80410a9f453f68e520";
      };
    };
    displayName = "Google Play XR Intel x86_64 Atom System Image";
    path = "system-images/android-34/google-xr/x86_64";
    license = {
      id = "android-googlexr-license";
      hash = "ceff83576aac4f7f37cb98fe189e9fb3c49d3b81";
    };
    xml = ./system-images-android-34-google-xr-x86-64.xml;
  };
  system-images-android-34-google-playstore-tablet-arm64-v8a = mkSrcOnly {
    id = "system-images;android-34;google_playstore_tablet;arm64-v8a";
    pname = "system-images-android-34-google-playstore-tablet-arm64-v8a";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/arm64-v8a-34_r02.zip";
        sha1 = "6f9bac7c3ce34a395ad7dee3dd09cce5df2cc194";
      };
    };
    displayName = "Google Play Tablet ARM 64 v8a System Image";
    path = "system-images/android-34/google_playstore_tablet/arm64-v8a";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-34-google-playstore-tablet-arm64-v8a.xml;
  };
  system-images-android-34-google-playstore-tablet-x86-64 = mkSrcOnly {
    id = "system-images;android-34;google_playstore_tablet;x86_64";
    pname = "system-images-android-34-google-playstore-tablet-x86-64";
    version = "2";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/x86_64-34_r02.zip";
        sha1 = "5be435ac140db34d0baf1be558aa8b3e63d27d79";
      };
    };
    displayName = "Google Play Tablet Intel x86_64 Atom System Image";
    path = "system-images/android-34/google_playstore_tablet/x86_64";
    license = {
      id = "android-sdk-preview-license";
      hash = "84831b9409646a918e30573bab4c9c91346d8abd";
    };
    xml = ./system-images-android-34-google-playstore-tablet-x86-64.xml;
  };
  system-images-android-35-google-apis-playstore-tablet-arm64-v8a = mkSrcOnly {
    id = "system-images;android-35;google_apis_playstore_tablet;arm64-v8a";
    pname = "system-images-android-35-google-apis-playstore-tablet-arm64-v8a";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/arm64-v8a-35_r09.zip";
        sha1 = "0023d7e13abc851b874592b1e64ac0bfd19eb627";
      };
    };
    displayName = "Google Play Tablet ARM 64 v8a System Image";
    path = "system-images/android-35/google_apis_playstore_tablet/arm64-v8a";
    license = {
      id = "android-sdk-arm-dbt-license";
      hash = "859f317696f67ef3d7f30a50a5560e7834b43903";
    };
    xml = ./system-images-android-35-google-apis-playstore-tablet-arm64-v8a.xml;
  };
  system-images-android-35-google-apis-playstore-tablet-x86-64 = mkSrcOnly {
    id = "system-images;android-35;google_apis_playstore_tablet;x86_64";
    pname = "system-images-android-35-google-apis-playstore-tablet-x86-64";
    version = "9";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/sys-img/google_playstore_tablet/x86_64-35_r09.zip";
        sha1 = "97b45ee880a29322224bbae2d36a979297d2e3e3";
      };
    };
    displayName = "Google Play Tablet Intel x86_64 Atom System Image";
    path = "system-images/android-35/google_apis_playstore_tablet/x86_64";
    license = {
      id = "android-sdk-license";
      hash = "24333f8a63b6825ea9c5514f83c2829b004d1fee";
    };
    xml = ./system-images-android-35-google-apis-playstore-tablet-x86-64.xml;
  };
}