# Generated by nix-android-repo

{ mkBuildTools
, mkCmdlineTools
, mkEmulator
, mkNdk
, mkNdkBundle
, mkPlatformTools
, mkPrebuilt
, mkTools
, mkSrcOnly
}: {
  add-ons-addon-google-gdk-google-19 = mkSrcOnly {
    id = "add-ons;addon-google_gdk-google-19";
    pname = "add-ons-addon-google-gdk-google-19";
    version = "11";
    sources = {
      all = {
        url = "https://dl.google.com/android/repository/glass/google-gdk.zip";
        sha1 = "52cadbec4d42ce68a667e7e4ea461ef8b81924ef";
      };
    };
    displayName = "Glass Development Kit Preview";
    path = "add-ons/addon-google_gdk-google-19";
    license = {
      id = "google-gdk-license";
      hash = "33b6a2b64607f11b759f320ef9dff4ae5c47d97a";
    };
    xml = ./add-ons-addon-google-gdk-google-19.xml;
  };
}